### ISSUE TITLE
Consider reusing libs on current virtualenv

### ISSUE THREAD

**Issue by rondineli-geru** [spotify/dh-virtualenv#100]
For projects with many libs, the time for installing libs how: numpy and scipy is long time!
Consider use libs on current virtualenv and no compiling all requirements on project again.

**Comment by jhermann** [comment]
That would greatly add to the build complexity and fragility. The right solution here is to use the new pip7 wheel cache, and/or a wheelhouse (e.g. devpi + devpi-builder) if you're in a corporate environment (or want to spend the time on setting up the infrastructure for personal use).

**Comment by nailor** [comment]
Upgrading pip is actually possible by using the `--preinstall` flag.

As @jhermann said, the fulfilling this feature would add complexity to the software. However one can work around this by using the wheel caches (if one is willing to setup it) or by allowing system packages (if that is OK for the case)

I'm closing this as an issue that should be tackled outside the dh-virtualenv.

**Comment by rondineli-geru** [comment]
Only for information:

I managed to install my dependencias with shorter time, i used **override_dh_virtualenv** and input parameters how: **---extra-pip-args** for using wheel and **--preinstall** for upgrade the current pip version. Worked for me! My debian/rules:
```
#!/usr/bin/make -f

#./packages/ is my folder with compiled requirements with wheel 
override_dh_virtualenv:
        dh_virtualenv --preinstall='pip==7.1.0' --extra-pip-arg='--use-wheel' --extra-pip-arg='--allow-all-external' --extra-pip-arg='--find-links=./packages/'

%:
        dh $@ --with python-virtualenv  --buildsystem=dh_virtualenv --use-system-packages
``` 

Tks !
