### ISSUE TITLE
support upgrading pip and setuptools before installing dependency packages

### ISSUE THREAD

**Issue by williamwu0220** [spotify/dh-virtualenv#101]
Dear sir,

It would be nice if dh-virtualenv supports upgrading pip and setuptools before installing dependency packages, for example:

dh $@ --with python-virtualenv --upgrade-pip --upgrade-setuptools

Because we encountered a problem, which needs upgrade pip and setuptools before installing packages listed in requirements.txt to solve the issue.

**Comment by jhermann** [comment]
That's already in there… https://github.com/Springerle/dh-virtualenv-mold/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/rules#L14-L15

**Comment by nailor** [comment]
Thanks @jhermann for answering once again! :)

I'm closing this issue as the feature is covered by the `--preinstall` flag (as pointed by @jhermann)
