### ISSUE TITLE
dh_virtualenv....deb package

### ISSUE THREAD

**Issue by cornelinux** [spotify/dh-virtualenv#102]
Obiously I missed something. But today I am blind.
What is the recommended way to build a debian package from dh_virtualenv itself?
I did it before, but now I am lost.

**Comment by nailor** [comment]
Do you mean you want to package the dh-virtualenv?

We [document the buliding by hand](https://dh-virtualenv.readthedocs.org/en/0.9/tutorial.html#step-1-install-dh-virtualenv), is that what you are looking for?

**Comment by cornelinux** [comment]
Exactly that! Thanks a lot!
