### ISSUE TITLE
SSL module not available

### ISSUE THREAD

**Issue by binary-koan** [spotify/dh-virtualenv#104]
Hi,
I'm trying to use python-requests in an app and distribute it with dh-virtualenv, but I'm getting an exception when trying to use HTTPS: "Can't connect to HTTPS URL because the SSL module is not available."

From what I've read, it sounds like this is because dh-virtualenv doesn't include a copy of the builtin SSL library - is that correct? And if so, is there any way to selectively add standard modules such as SSL to a dh-virtualenv build?

Thanks

**Comment by nailor** [comment]
Hi,

are you sure you have all the needed runtime libraries available on the host you are running it? So far I haven't seen any issues with the requests and dh-virtualenv.

**Comment by binary-koan** [comment]
Thanks for the reply - I did actually solve this and forgot to close the issue. In the end, putting pyOpenSSL explicitly in requirements.txt worked (in case anyone else has the same problem) but I think it also had to do with building the package on Ubuntu 15.04 and trying to deploy on a 12.04 server ...
