### ISSUE TITLE
time to release a 0.10?

### ISSUE THREAD

**Issue by sandrotosi** [spotify/dh-virtualenv#105]
Hi, sorry I dunno how to actually request to issue a new release (there are a ton of cool features in git which I'd like to use) so I open this ticket

**Comment by nailor** [comment]
Hey @sandrotosi and thanks for the issue!

We got a few nice fixes in that warrant for a new release, so I'll get onto it!

**Comment by nailor** [comment]
And 0.10 is released! It just got accepted to Debian Unstable, so accept to see it there in a moment :)

**Comment by sandrotosi** [comment]
awesome, thx! I guess you can also close #793378

are you interested in backporting it to jessie and wheezy or do you prefer for me to do it?

**Comment by nailor** [comment]
If you can do it, that would be highly appreciated! :)

**Comment by nailor** [comment]
And I don't think I have the possibilities of closing bugs (not too familiar with the Debian bug tracking system myself)

**Comment by sandrotosi** [comment]
I will backport it then (once it reaches testing).

as for closing bug, the right thing would have been to close it during the upload, just adding 'Closes: #793378) in the changelog entry.

now you can simply mail 793378-done@bugs.debian.org (with some explanation) to close it
