### ISSUE TITLE
Using dh-virtualenv in Jenkins?

### ISSUE THREAD

**Issue by ariscn** [spotify/dh-virtualenv#110]
I'm trying to use dh-virtual with http://jenkins-debian-glue.org/. I'm having some trouble because I need dh-virtualenv > 0.7, but Ubuntu has 0.6. I've installed 0.10 via your PPA, but this isn't visible to the chroot used for the build.

Do you have any tips on how to drop dh-virtualenv (either the PPA or built package) in?

**Comment by ariscn** [comment]
Because `jenkins-debian-glue` builds in a chroot, I need to add the dh-virtualenv PPA into the base cow used by cowbuilder. I did this with `sudo cowbuilder --login --basepath=/var/cache/pbuilder/<my copy of base>.cow --save-after-login`. Now, I'm seeing the following:

```
dh clean --with python-virtualenv
sh: 1: cannot create /dev/null: Permission denied
   dh_testdir
   dh_clean
 dpkg-source -b ingest-controller-2.0.44+0~20150911173238.10~1.gbpf00d2e
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format `1.0'
dpkg-source: info: building ingest-controller in ingest-controller_2.0.44+0~20150911173238.10~1.gbpf00d2e.tar.gz
dpkg-source: info: building ingest-controller in ingest-controller_2.0.44+0~20150911173238.10~1.gbpf00d2e.dsc
 debian/rules build
dh build --with python-virtualenv
sh: 1: cannot create /dev/null: Permission denied
   dh_testdir
   dh_auto_configure
 fakeroot debian/rules binary
dh binary --with python-virtualenv
sh: 1: cannot create /dev/null: Permission denied
   dh_testroot
   dh_prep
   dh_installdocs
   dh_installchangelogs
   dh_installinit
   dh_perl
   dh_virtualenv
New python executable in debian/ingest-controller/usr/share/python/ingest-controller/bin/python
Installing setuptools, pip...done.
sh: 1: cannot create /dev/null: Permission denied
```

This is followed by a big stack of more /dev/null Permission denied messages.

Any thoughts on how to fix this?

**Comment by nailor** [comment]
Is it not an option to modify the chroot to include the package or the PPA?

**Comment by jhermann** [comment]
The point of using cow/pbuilder is the pristine build environment, so all dependencies are checked for correctness – what actually helps is to add dh-virtualenv to the build-depends, and modify the chroot to have an APT source you can get it from.

**Comment by nailor** [comment]
I'm closing this issue since it is not related to dh-virtualenv directly.
