### ISSUE TITLE
PPA support

### ISSUE THREAD

**Issue by noplay** [spotify/dh-virtualenv#112]
It's not really an issue but I document it for people who want to build with dh-virtualenv on Ubuntu ppa. The main issue is ppa builder doesn't have access to the internet when building from the source package. The trick is to cache package in the source file uploaded to PPA and use this cache instead of PyPi.

1) Add the dh-virtualenv ppa as dependencies of your ppa
2) Download pip package to your local computer

```
mkdir debian/pypi
pip3 install  --download debian/pypi -r requirements.txt
```

3) Edit your rules file for something like that:

```
#!/usr/bin/make -f

%:
    dh $@ --with python-virtualenv

override_dh_virtualenv:
    dh_virtualenv --extra-pip-arg "--no-index" --extra-pip-arg "--find-links=file://${PWD}/debian/pypi
```

**Comment by nailor** [comment]
This is pretty great, good tips :)

I'm looking into (finally) creating the tips and tricks section to the documentation, this could be included there. I'll leave the issue open until it is documented somewhere :)

**Comment by josharenson** [comment]
@noplay I was trying to figure out an elegant solution to this for hours. Thank you so much, this works perfectly and should be included in the cookbook as I'm sure building packages in internet isolated chroots is common.

**Comment by nailor** [comment]
Closing the issue, for now this can work as a documentation
