### ISSUE TITLE
Including package data (eg HTML templates)

### ISSUE THREAD

**Issue by codeinthehole** [spotify/dh-virtualenv#113]
I'm having trouble getting the built `.deb` file to include the package data, in this case HTML template files.  

I have a `setup.py` like:

```python
#!/usr/bin/env python
from setuptools import setup, find_packages
import os

setup(
    name='some-package',
    version='0.1',
    package_dir={'': 'src'},
    packages=find_packages('src'),
    include_package_data=True,
)
```
and a `MANIFEST.in` file like:

```
recursive-include src/templates *.txt *.html
recursive-exclude src/tests *
```

Running `python setup.py sdist` builds the correct package locally, including the templates and ignoring the tests. But something different happens when I build the `.deb` package.

Since I'm an OSX user, I run packaging on a vagrant box (not sure if that's relevant at all). The output from `dpkg-buildpackage -us -uc` indicates that the `MANIFEST.in` file is being read but the final package doesn't include the HTML files.

Snippet from `dpkg-buildpackage` output:

```bash
$ cd /vagrant/ && sudo dpkg-buildpackage -us -uc
...
running egg_info
creating src/some-package'.egg-info
writing src/some-package'.egg-info/PKG-INFO
writing top-level names to src/some-package'.egg-info/top_level.txt
writing dependency_links to src/some-package'.egg-info/dependency_links.txt
writing manifest file 'src/some-package'.egg-info/SOURCES.txt'
reading manifest file 'src/some-package'.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt' under directory 'src/templates'
writing manifest file 'src/some-package'.egg-info/SOURCES.txt'
...
creating build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/__init__.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/conftest.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/decorators.py -> build/bdist.linux-x86_64/egg/tests
copying build/lib.linux-x86_64-2.7/tests/factories.py -> build/bdist.linux-x86_64/egg/tests
...
```
There's no reference to coping the template files into place and, as you can see, the test files are copied (when I think they should be excluded).

Any thoughts on what I'm doing wrong?

**Comment by nailor** [comment]
Do you have the full output? I'm interested in do those files get moved into the correct place or not. Files defined via package_data mechanism should be included.

Another, a bit more blunt way, is to use `debian/install` to explicitly install those files.

**Comment by codeinthehole** [comment]
> Do you have the full output?

Sorry, I don't. There was no reference to the HTML files in the output though.

I worked around this by restructuring my package. I moved the `templates/` folder into the python package folder (rather than being along side), removed `MANIFEST.in` and adjusted `setup.py` to:

```python
#!/usr/bin/env python
from setuptools import setup, find_packages
import os

setup(
    name='some-package',
    version='0.1',
    package_dir={'': 'src'},
    packages=find_packages('src', exclude=["*tests*"]),
    package_data={
        'mypackage': ['templates/*.html', 'templates/**/*.html']
    },
)
```
Then the HTML files were correctly picked up.

**Comment by jhermann** [comment]
BTW, this is easily explained – the manifest only influences the sdist result, but what gets included is the binary package (i.e. a wheel or egg). `package_data` OTOH describes / extends the contents of the binary package.

**Comment by jhermann** [comment]
PS: On a related matter, it'd be nice if we had a substvar for the main package path, or the site-packages dir. In one of my packages, I have this in the `*.links` file:

    # Shortcuts
    opt/foobar/lib/python2.7/site-packages/foobar opt/foobar/_pkgdir

I can then use `_pkdir` in other link paths to avoid the endless repetition of that long path. Which still leaves the problem the path contains the Python version, a substvar would be way nicer.

**Comment by nailor** [comment]
Thanks for @jhermann answering this one! I'm closing the issue :)

**Comment by lamby** [comment]
> the manifest only influences the sdist result, but what gets included is the binary package (i.e. a wheel or egg). package_data OTOH describes / extends the contents of the binary package.

I'm having awful trouble getting setuptool's ``package_data`` to be included in the final binary. Are we sure this is working? :)  I don't / can't move the files inside the python package folder, alas.

**Comment by nailor** [comment]
Do you happen to have an example of your package somewhere?

**Comment by jhermann** [comment]
@lamby This is what should help you, do you have the *extra* non-source paths listed like this?

    package_data={
        'mypackage': ['templates/*.html', 'templates/**/*.html']
    },

`include_package_data` alone just addresses files that are an integral part of the source tree.

**Comment by lamby** [comment]
@jhermann Yes. Tried all sorts of combinations of `['templates/*.html', 'templates/**/*.html']`.

Let me make a minimal testcase in the next couple of days and get back to you.

**Comment by jhermann** [comment]
Another idea of a possible cause: if you don't add the same patterns to your MANIFEST, the data files are missing from the sdist, which might have consequences…

**Comment by adi-** [comment]
@jhermann relating to main package path 

```
# Shortcuts
opt/foobar/lib/python2.7/site-packages/foobar opt/foobar/_pkgdir
```

I see similar issues. When my package is installed it lands in `foobar_1.x.x' folder. This is ridiculous when your logic relies on using your package dir. I.e. I am using Gunicorn which needs to run in package's dir. That sux, because when my package is updated, I need to change dir in gunicorn's confog files.

P.S. Is there any chance to use `sdist` rather than `build` ???

**Comment by jhermann** [comment]
If you mean using the sdist built from the workdir to create the DEB, instead of installing the workdir directly, look at 

https://github.com/Springerle/dh-virtualenv-mold/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/rules

And your versioning issue is quite probably a defect of your project, not something dh-virtualenv introduces.
