### ISSUE TITLE
Provide a substvar that references the virtualenv base directory

### ISSUE THREAD

**Issue by nailor** [spotify/dh-virtualenv#115]
In order to make creating links and others easier, provide a substvar that points to the base virtualenv.

Thanks @jhermann for suggesting this :)

**Comment by jhermann** [comment]
Just to clarify, the main use-cases I have require the `site-packages` path of the installed virtualenv to be available, due to it being a) long, and b) dynamic (includes the interpreter's version number).

Basically where you'd use `__file__` or `__path__` in a script, but within the scope of the files in `debian`.

**Comment by nailor** [comment]
Looking at the [man page of deb-substvars](http://manpages.ubuntu.com/manpages/precise/man5/deb-substvars.5.html) it looks like the traditional substvars won't apply to the `links` or `install`.

**Comment by lamby** [comment]
> it looks like the traditional substvars won't apply

What other kind were you thinking of?

I can't see how the `debian/control` in the binary package containing, say, the `site-packages` path would be really/cleanly consumable by your application, but perhaps I'm missing something.

**Comment by nailor** [comment]
Thinking of easing writing the `install` and `links` files. Say you want to create a symlink from the binary folder, it currently looks something like this in `debian/links`

```
usr/share/python/the-package-name-that-can-be-really-long/bin/the-binary-name /usr/bin/the-binary-name
```

If you want to link or install stuff under site-packages, it gets even longer. And it depends on the (minor) version of the interpreter, so changing interpreter means that you need to rewrite these files.

**Comment by lamby** [comment]
Right.. But as I asked: how, exactly, could a substvar work here? They
are a dpkg-gencontrol concern, not a debhelper one.

On Mon, 12 Oct 2015, at 08:11 AM, Jyrki Pulliainen wrote:
> Thinking of easing writing the `install` and `links` files. Say you want
> to create a symlink from the binary folder, it currently looks something
> like this in `debian/links`
> 
> ```
> usr/share/python/the-package-name-that-can-be-really-long/bin/the-binary-name
> /usr/bin/the-binary-name
> ```
> 
> If you want to link or install stuff under site-packages, it gets even
> longer. And it depends on the (minor) version of the interpreter, so
> changing interpreter means that you need to rewrite these files.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spotify/dh-virtualenv/issues/115#issuecomment-147307208


-- 
Chris Lamb
chris-lamb.co.uk / @lolamby

**Comment by nailor** [comment]
ah, yeah, the traditional substvars won't work there indeed.

I don't know if there are some other tools that Debian packaging supports or if one needs to roll their own (which can be problematic)

**Comment by lamby** [comment]
Always helps to read carefully what people write ;)  dh-exec may be what
you are after. Hang on, why not use setup.py package_data to install
stuff here? Won't work for, say, templating a systemd .service file, but
should work for most use cases.

On Mdaten, 12 ct 2015, at 12:06 PM, Jyrki Pulliainen wrote:
> ah, yeah, the traditional substvars won't work there indeed.
> 
> I don't know if there are some other tools that Debian packaging supports
> or if one needs to roll their own (which can be problematic)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/spotify/dh-virtualenv/issues/115#issuecomment-147366904


-- 
Chris Lamb
chris-lamb.co.uk / @lolamby

**Comment by nailor** [comment]
Closing this rather old issue as, as far as I know, there is no built in variable support in install and links files that could be leveraged
