### ISSUE TITLE
Builds take a long time - are there any speedups?

### ISSUE THREAD

**Issue by codeinthehole** [spotify/dh-virtualenv#116]
_This isn't a bug per se, more a mailing list style question but I don't think there's a mailing list._

I find building a simple package on a Vagrant box takes a long time (~10 minutes) - is this normal? The box has a 1G of memory and the process doesn't seem to be memory bound (eg bumping to 2G makes no difference). 

I also run a local devpi instance to cache PyPI downloads.

Is there anything I can do to speed this up?

**Comment by nailor** [comment]
It varies, depending on what you build and how. For example if you install some certain packages from sources that requires compiling extensions, it can take a while.

However, there are a few ways to mitigate that. First make sure you run recent enough pip in builds. That can be done with the `--preinstall` flag. That way the pip caches packages it builds as wheels, next you only need to make sure the wheel cache is available for the subsequent builds.

You can also make the devpi a wheel cache, using devpi client you can upload wheels for the packages. Unfortunately that can't be done on the pypi mirror (root/pypi index), but needs to be done on a custom index with whitelisting.

**Comment by jhermann** [comment]
Make sure you use pip7, i.e. `--preinstall "pip>7" --preinstall wheel"`. And/or seed your devpi with wheels of your dependencies.

**Comment by nailor** [comment]
Closing this ticket, since there are some instructions for speedups provided
