### ISSUE TITLE
ability to reference local code projects in requirements.txt

### ISSUE THREAD

**Issue by filler** [spotify/dh-virtualenv#117]
Hello --

dh-virtualenv is pretty great.  Thanks for that.  :smile: 

One thing we have found ourselves wanting to do is to is to be able to list a local tree in `requirements.txt` for satisfying on venv build.  The idea here is we have modules which are 'private' and we dont run pypiserver or devpi.  We thought we could just list `-e dir-with-non-pypi-python-code` in `requirements.txt`, which works great when its pip.  However in dh-virtualenv we bomb with the following:

```
error in setup command: 'install_requires' must be a string or list of strings containing 
valid project/version requirement specifiers; Expected version spec in 
-e dir-with-non-pypi-python-code at  dir-with-non-pypi-python-code`
```

I assume this is attributed to fakeroot but Im at a loss on how to debug further.  

Insight appreciated.  Thanks.

**Comment by nailor** [comment]
Which pip version are you running in the builds? I can't think any reason why `-e` should not work. Fakeroot shouldn't block it, as the error feels like it is from setuptools.

Are you sure you are not doing any requirements.txt parsing in setup.py and entering that into the install_requires?

**Comment by Ivoz** [comment]
Q: why is your requirements.txt being inserted verbatim into `install_requires`? They are not compatible.

**Comment by ionrock** [comment]
@nailor @Ivoz I've been working with @filler on this one. 

This project uses pbr, which means that doing `pip install .` ends up slurping up the requirements.txt, in which case `-e path/to/foo` is not a valid version spec. We're looking at solutions using the available flags and will comment if there seems to be a better or good work around. 

Thanks!

**Comment by Ivoz** [comment]
You could try *not* using pbr, so requirements.txt and install_requires don't get confused like that. pbr should feel bad for confusing them.

https://caremad.io/2013/07/setup-vs-requirement/

**Comment by ionrock** [comment]
@Ivoz I wish I could! It is an OpenStack project, so pbr is a requirement. I'm looking into the buildsystem support and more recent flags (we were using 6.1) to get around pbr's issues. Thanks!
