### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by rkubik** [spotify/dh-virtualenv#122]
Hi,

Having issues building virtual env's for Python3, does dh-virtualenv support it? If not, will it?

    File "/usr/bin/dh_virtualenv", line 29, in <module>
    from debpython.debhelper import DebHelper
    File "/usr/share/python/debpython/debhelper.py", line 205
    chmod(fn, 0755)

I notice that `/usr/bin/dh_virtualenv` adds `/usr/share/python` to the `PYTHONPATH` but for python3 the debhelper scripts sit in `/usr/share/python3/debpython` and have changed significantly.

**Comment by evilaliv3** [comment]
@rkubik why have you opened then closed this ticket?

i would also be interested in this! :)

**Comment by evilaliv3** [comment]
ah ok, the support already exists and this ticket is duplicated of https://github.com/spotify/dh-virtualenv/issues/99

@nailor i read in https://dh-virtualenv.readthedocs.org/en/latest/usage.html#known-incompabilities-of-the-buildsystem "Pyvenv of Python 3.x is not supported"

probably it should be removed? i see infact that in #99 you say that python3 is now supported

**Comment by nailor** [comment]
@evilaliv3 Yeah, you're right. The whole section is actually wrong, all of those cases are supported :)

**Comment by jhermann** [comment]
- https://dh-virtualenv.readthedocs.io/en/latest/howtos.html#building-packages-for-python3
- https://github.com/1and1/debianized-jupyterhub/blob/master/debian/rules

**Comment by tux-mind** [comment]
dh_virtualenv is a python2 script. Therefore you have to execute it with python2 in the first place:

`debian/rules` file:

```
override_dh_virtualenv:
	python2 $(shell which dh_virtualenv) --python python3
```

Cheers :)
