### ISSUE TITLE
Buildsystem questions

### ISSUE THREAD

**Issue by einarf** [spotify/dh-virtualenv#131]
It's not entirely clear to me how to do the following when using the buildsystem :
* Specify requirement file. If I'm not looking in the wrong place, 'requirements.txt' is hardcoded.
* Add extra arguments to pip

The bits about incompabilities of the buildsystem was removed recently. Not sure what I missed :)

**Comment by einarf** [comment]
A quick fix 5 minute fix was to hack in som extra env vars : f4cb85cbf088d0fcddcf53ea214ddae5caa9e772

Not sure if that is too crazy.

**Comment by nailor** [comment]
I actually removed the documentation of differences since it was mainly confusing people with recurring questions about what we support and where.

The changes to me look solid. Would you like to submit them as a PR?

**Comment by einarf** [comment]
Sure. I'll make a PR very soon.

**Comment by einarf** [comment]
I've tested this in all cases to make sure nothing breaks.

**Comment by nailor** [comment]
No prob, docs look great and thanks for testing. Would be interesting to come up with some sort of automated test suite for this stuff though, but since Debian packaging is involved, it might be tough

**Comment by nailor** [comment]
I'm closing this btw in favor of the #132

**Comment by jhermann** [comment]
Regarding automatic testing, see https://github.com/Springerle/dh-virtualenv-mold/blob/master/test.sh

Should work in Travis too.
