### ISSUE TITLE
problems with building

### ISSUE THREAD

**Issue by musicformellons** [spotify/dh-virtualenv#135]
I am on Ubuntu 15.10 using pyenv. First tried apt-get install; works but gives version 7.1, seems old so I tried to use the repo to get version 11.1 , it does not work probably because I am on Wily instead of Trusty. Then tried to build with given instructions and get error:
build succeeded, 4 warnings.
dh_installdocs doc/_build/html
make[1]: Leaving directory '/home/usr/dh-virtualenv'
   dh_sphinxdoc
dh_sphinxdoc: error: unknown JavaScript code: debian/dh-virtualenv/usr/share/doc/dh-virtualenv/html/_static/jquery.js
debian/rules:4: recipe for target 'binary' failed
make: **\* [binary] Error 255
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

As it says build succeeded but continuing gives:
usr@xps:~/dh-virtualenv$ sudo dpkg -i ../dh-virtualenv_<0.11>.deb
bash: 1.1: No such file or directory

**Comment by jhermann** [comment]
Old, assuming resolved (also see #202).
