### ISSUE TITLE
How to build separate deb packages for my project and for its virtualenv?

### ISSUE THREAD

**Issue by nilstoedtmann** [spotify/dh-virtualenv#138]
I have a relatively small python project "myapp" which needs to run in a comparably large virtualenv. Because this is for embedded devices with poor mobile uplinks, and because myapp is changing much faster than its requirements.txt, I'd like to generate two deb packages: a small one only containing myapp which depends on a larger myapp-virtualenv.

Is there a relatively straightforward way to achieve this?

(Sorry to abuse the issue tracker for a simple question. I didn't see a mailing list or chat channel mentioned)

**Comment by nailor** [comment]
No worries! Since neither of those exist, I think the issue tracker is good enough to keep tabs on different problems with usage :)

You could build the package and then use install files to point the build files to two separate packages.

**Comment by jhermann** [comment]
The way I do this, to support running "custom scripts" against a library that comes with "standard scripts" (entry points), is to have a uniquely named link to the venv Python.

    $ cat debian/myapp.links 
    opt/myapp/bin/python				usr/bin/myapp-python

Then just start your scripts with `#! /usr/bin/env myapp-python` and package them e.g. using fpm (they're single-file packages).

This and other tickets like it should probably be added to a tips&tricks chapter in the docs.

**Comment by nilstoedtmann** [comment]
Thx guys. I am relatively new to Debian and Python packaging (did a fair amount or rpm packaging years ago), so further details would be appreciated ("_... use install files to point the build files to two separate packages_"?). But I'll dig my way through either way :-)

**Comment by jhermann** [comment]
You could do that, but happy hunting for all the right debian/* magic to get this working.

As I said, I'd use https://github.com/jordansissel/fpm for those aux / script packages, especially since you wouldn't want to always pack your big base venv anyway. Use a for loop in an Invoke `tasks.py` or something to build them.

**Comment by nailor** [comment]
@nilstoedtmann you can define `debian/<packagename>.install` and list in that file what files should be installed for that package. It has two formats (both can be used in the same file):

1. Specify which file(s) to install where
```
some/local/path usr/lib/some/path/on/targe/machine
```

2. Specify what to include in the package. Following would for example instruct that the package should have the `venv` and everything under it included (say you would put this in `debian/mypackage-virtualenv.install`:
```
usr/share/python/mypackage/venv
```

The latter is probably what you want, listing directories which (incl. their subdirectories) should be installed in the package. You also need all the packages defined in the control file under `debian/control`.

Or you go with fpm, which I'm not too familiar with, but should get the job done :)
