### ISSUE TITLE
unable to handle module name with the underscore

### ISSUE THREAD

**Issue by sandrotosi** [spotify/dh-virtualenv#145]
while creating a venv with this module

```
ipy_table==1.12
```

i got this error while building it:

```
Downloading/unpacking ipy-table==1.12 (from -r requirements.txt (line 53))
  Could not find a version that satisfies the requirement ipy-table==1.12 (from -r requirements.txt (line 53)) (from versions: )
No distributions matching the version for ipy-table==1.12 (from -r requirements.txt (line 53))
```

like if the '_' got replaced by a '-' . there are about 20k modules on pypi with an underscore in their name (https://pypi.python.org/pypi?%3Aaction=search&term=_&submit=search) so it would be great if that could be supported.

thanks!

**Comment by nailor** [comment]
Hi,

this is due to a behaviour of an older pip version. I'm betting you are running the 1.5.4 or similar version. I'd suggest upgrading pip either using `--preinstall pip==<some-newer-version>` or to use the new `--upgrade-pip` flag of the (unreleased) latest dh-virtualenv

**Comment by sandrotosi** [comment]
hey @nailor sorry for replying only now, I'm trying to preinstall pip (as suggested) but I am unable to find the right way to do it when using ```--buildsystem=dh_virtualenv```: I tried

```
override_dh_virtualenv:
            dh_virtualenv --preinstall pip==X.Y.Z
```
but it appears to have no effect, i tried also with

```
override_dh_auto_build:
       dh_virtualenv --preinstall pip==X.Y.Z
       dh_auto_build
```

but that's basically like running --with=python-virtualenv (as it skips all the overrides, and we dont want that).

Can you suggest a way to --preinstall with --buildsystem=dh_virtualenv ?

thanks!

**Comment by nailor** [comment]
Since the buildsystem support has sort of taken a back seat, it is missing many of these features at the moment.

If you can build package with the 'traditional' method, I suggest trying that out, since porting of the existing features to the buildsystem side is a quite a feat and at the moment it is not being worked on (for what I know).

**Comment by sandrotosi** [comment]
just to update this, we converted our package to the dh sequencer and we were able to use the --preinstall and thus also be able to install modules with an underscore in their name. Thanks @nailor for your support!!

**Comment by nailor** [comment]
No problem! Good to hear you got your issue sorted out!
