### ISSUE TITLE
PPA for Ubuntu 12.04 Precise

### ISSUE THREAD

**Issue by zyv** [spotify/dh-virtualenv#147]
Hi,

I understand that there is an official PPA which publishes packages for Ubuntu 14.04 Trusty:

https://launchpad.net/~spotify-jyrki/+archive/ubuntu/dh-virtualenv

However, unfortunately, there doesn't seem to be any builds available for Ubuntu 12.04 Precise.

Could you please be so kind to look into doing a build for Precise for those of us who are still stuck with this LTS version?

Many thanks!

**Comment by nailor** [comment]
Hi,

I copied the package over to Precise.

Let me know if it works!

**Comment by zyv** [comment]
Thanks, I'll give it a try!

**Comment by nailor** [comment]
Closing this, please re-open if the precise image is not working
