### ISSUE TITLE
installing extra directories

### ISSUE THREAD

**Issue by kkvilekval** [spotify/dh-virtualenv#152]
I need to install an extra directory with extra configuration files (these are not python data files and are installed with the python package) located at the top-level of my repo but otherwise my package is a standard back..   If I use 

```
%:
	dh $@ --with python-virtualenv
```

Then I find the .deb actually has the virtualenv installed under the package name all looks good

Instead if I use 
```
%:
	dh $@ --buildsystem=dh_virtualenv

```

Then I get a pretty empty .deb file.   How do I get the virtualenv and the extra config directory installed?

**Comment by kkvilekval** [comment]
For future reference.. when using buildsystem=dh_virtualenv, you must just include 

debian/_package_.install:
`debian/tmp/*  
`

to get anything into the package

**Comment by corentingi** [comment]
I've had some trouble adding extra files in the package.

The solution was to add a `debian/install` file using the install dh_install file syntax:
```
my-service.service /etc/systemd/system/
```
