### ISSUE TITLE
adding arguments when using buildsystem?

### ISSUE THREAD

**Issue by kkvilekval** [spotify/dh-virtualenv#154]
When using 
```
%:
	dh $@ --buildsystem=dh_virtualenv
```

how does one add --upgrade-pip ?

**Comment by einarf** [comment]
Don't think that works with buildsystem as you can only pass in env variables mentioned in the docs.

**Comment by nailor** [comment]
Yeah, as @einarf said, the buildsystem does not unfortunately support `--upgrade-pip`.

Thanks for your issue, maybe I should look into documenting what's supported and what is not for the buildsystem approach.
