### ISSUE TITLE
Generate service files ?

### ISSUE THREAD

**Issue by jpic** [spotify/dh-virtualenv#157]
Hi all !

Thanks a lot for sharing dh-virtualenv, it makes generating debian packages really quick'n'easy !

In sbt/sbt-native-packager, the equivalent for scala apps, they generate service files too, do you think it would be useful to try to have such feature in dh-virtualenv ?

Thanks for your feedback !

**Comment by nailor** [comment]
Hi! Do you mean things like files for system.d/upstart? That should be (somewhat) trivial by just including relevant files under the `debian/` directory, for example `debian/myservice.upstart` will end up being upstart configuration for the myservice. 

Don't know if generating those automatically would be easy though.

**Comment by jhermann** [comment]
If someone delivers the templates, I can add them to https://github.com/Springerle/dh-virtualenv-mold/

I don't think such things belong into the tool itself.

**Comment by jpic** [comment]
Thanks for your feedback, perhaps this would rather be part of something that's sitting above dh-virtualenv. Anyway, will give it a try in the following days and open a PR which we'll be able to evaluate fully.
