### ISSUE TITLE
Followup from #82 -- change the default location based on executable name

### ISSUE THREAD

**Issue by asottile** [spotify/dh-virtualenv#159]
We're also running into the exact issue in #82.

Wondering if you'd be amenable to a patch which does something like this:

Use `/usr/share/$exename` for the install location -- that is if I'm using no arguments it'll still use /usr/share/python, but if I select (for example `--python=/usr/bin/python3.5`) it'll install into /usr/share/python3.5

**Comment by jhermann** [comment]
The whole point of picking up the "default" part of #82 is to *avoid* these bad defaults (they are prone to incur problems), and use something that does not overlap with Debian structures.

**Comment by bobtfish** [comment]
I vote with *any of these* - I would just like to stop the case which shot us in the foot where installing a package built against python 3 will stop you ever being able to subsequently install or upgrade system python ;)

**Comment by nailor** [comment]
I'd actually love to change the default, but I'm worried about breaking builds when doing that. Currently there is an option for defining the install root, that should help with the problem in hand. 

Not too keen on picking up something with magic either, since that will probably backfire at some point.

**Comment by jhermann** [comment]
Well, 0.x somehow implies breakage. ;)

I think going to 0.20 should give a hint even to those that don't read the changelog.

**Comment by nailor** [comment]
Yeah, or do the change and call it 1.0 finally. And frankly the projects I care most are our internal ones, and there I can help fixing quite a lot :)

**Comment by asottile** [comment]
I'd be cool with `/opt/virtualenvs` or some static different path too :) maybe `/opt/dh-virtualenv-packages` or something to namespace it slightly?

**Comment by nailor** [comment]
Not sure if that gives any additional value, but please keep suggestions flowing! I'll also run this internally to find out if people have preferences on this.

**Comment by jhermann** [comment]
One input: do not make it too long (cf. shebang 127chars). We only need unique with a clear association to venvs, not "more unique". ;)

**Comment by bobtfish** [comment]
Strongly encourage changing the default. I'm gonna have to update dozens of packages anyway to fully solve the issues this causes internally (which is PITA, but fine).

However if the default doesn't get changed, I'm likely to end up back here (as someone else didn't pick up on the fact that the default is pointing a gun at their foot) a load more times.

It's possible to partially get around this by putting a huge notice in the documentation, but I'd suggest that if the docs suggest never using the defaults (and have to explain why the defaults are likely to hurt you), then it's probably better to change the defaults (even if it's a breaking change) to reduce the cognitive load on users.

**Comment by nailor** [comment]
Hi all,

sorry for the hiatus but just to keep you in the loop, I've asked people internally to comment on this change (both internally and if so deemed externally). I'll let you know when I have more results!

**Comment by nailor** [comment]
Hello! See #165 for the change including this. I opted for `/opt/venvs/` since it is shorter (`/opt/virtualenvs` is as long as `/usr/share/python`). Now we save whopping 8 characters from the shebang! :)

**Comment by chriskuehl** [comment]
+1 for moving the packages, but I don't really think `/opt` is an appropriate place for a Debian package to install things.

From `hier(7)`:

> `/opt`
> This directory should contain add-on packages that contain static files.

This isn't too useful, so let's see what Debian's wiki says:


> `/opt/`
> Add-on application software packages 
> Pre-compiled, non ".deb" binary distribution (tar'ed..) goes here.

The FHS later says that `/opt` is useful as a prefix for local administrators (`/opt/bin`, etc.).

I think that `/usr/share/<package>` is a better fit.

> `/usr/share`
>        This directory contains subdirectories with specific application data, that can be shared among different architectures of the same OS.  Often one finds stuff here that used to live in /usr/doc or /usr/lib or /usr/man.

Looking at `/usr/share` on Debian jessie, there are a lot of similar applications and data here to what dh-virtualenv is doing.

Further precedent: from doing an `apt-file` search, there isn't a single package in Debian stable right now which installs files into `/opt`.

**Comment by jhermann** [comment]
dh-venv packages are by their very nature not conforming to Debian Policy; if you go by precedence, look at omnibus packages like gitlab-ce, which also use /opt as the one collision-free space in the file system. Anything else clashes with trees that underlie the policy, including your suggestion.

**Comment by chriskuehl** [comment]
As long as it's configurable than I think it is fine, though I don't see why `/opt` is better than `/usr/share`.

**Comment by jhermann** [comment]
> This directory contains subdirectories with specific application data, that can be shared among different architectures of the same OS.

Not true if you package C extensions, besides the copy of the interpreter binary.

**Comment by bobtfish** [comment]
Any news here folks?

**Comment by nailor** [comment]
@bobtfish See #165, the change is included there. I'm still waiting for some other changes before moving forward with that PR, but might be that certain added features (customised pip command) shall be handled in a future version

**Comment by bobtfish** [comment]
This is great, thanks folks!
