### ISSUE TITLE
No way to specify files to exclude

### ISSUE THREAD

**Issue by zgoda** [spotify/dh-virtualenv#163]
In my package I have MANIFEST.in that prunes files I do not want to be included in package yet it is not processed at build time. I know I can exclude whole packages using exclude argument to find_packages() but for files only MANIFEST.in can be used.

**Comment by jhermann** [comment]
Try what I do, namely package from a pristine clone of the workdir created via ``sdist``.

See [here](https://github.com/Springerle/dh-virtualenv-mold/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/rules#L29-L33).

**Comment by nailor** [comment]
Thanks @jhermann for providing pointers on this.

Let me know if there's still something you think dh-virtualenv should handle and re-open the issue/create a new one. I'm closing this for now
