### ISSUE TITLE
Breaks with absolute data_files paths

### ISSUE THREAD

**Issue by sebschrader** [spotify/dh-virtualenv#164]
If you have a Python distribution that has data_files with absolute paths, `dh_virtualenv` does not work correctly. E.g.:

```python
from setuptools import setup

setup(name='foo',
      version='0.1',
      data_files=[
          ('/etc/foo/', ['foo.conf']),
      ],
      )
```

The `data_files` are not installed in the build directory. `pip` tries to install them below `/` on the host.

It tried playing with the `--root` argument of `pip` by e.g. supplying `--extra-pip-arg=--root=$(CURDIR)/debian/foo`, without any success.

**Comment by nailor** [comment]
This is a bit cumbersome to solve in a nice way in dh-virtualenv. It would require either parsing the `setup.py` to find out what gets installed in root (which is impossible to get right) or to chroot the whole installation in a directory.

I'd suggest removing the absolute paths form the `data_files` directive and using Debian's `install` files to move them into the correct location.
