### ISSUE TITLE
virtual environment not in deb

### ISSUE THREAD

**Issue by benman1** [spotify/dh-virtualenv#168]
Hi, 
 thanks for this tool. I've watched the intro talk on youtube, went through the tutorial, and a lot of what I could find online. This is the first time I am building a deb package, and I am not sure I understand the mechanics behind it yet. I am working with python3.4 which maybe makes it a bit more complicated. My problem is that the virtual environment does not seem to be included when I run dpkg -c package-name.deb. 

After patching up pyversions to return python3.4 (it doesn't return anything otherwise), I can run the install with different rules such as these: 

```
%:
        dh $@ --with python3 --builtin-venv
```

or 

```
%:
        dh $@ --with python3 --builtin-venv --buildsystem=pybuild
```

or 

```
%:
        dh $@ --with python3
```

I've tried a lot of things already. It does download python packages in some of these configurations, however I never see them in the deb. 

Please help!

**Comment by aRkadeFR** [comment]
Have you tried to add `python-virtualenv` in your `--with` argument?

For instance my debian `rules` looks like this:
```
%:
    dh $@ --with systemd,python-virtualenv

override_dh_virtualenv:
    dh_virtualenv --setuptools --python /usr/bin/python3
```

**Comment by benman1** [comment]
Hi again! 
 thanks for that. It goes much further now in the build process. However, now I have problems integrating scikit learn: 

       dh_strip
    [...]
    strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/packagename/usr/share/python/packagename/lib/python3.4/site-packages/sklearn/linear_model/sgd_fast.cpython-34m.so
    Not enough room for program headers, try linking with -N
    BFD: debian/packagename/usr/share/python/packagename/lib/python3.4/site-packages/sklearn/linear_model/stSBnUjs: Not enough room for program headers, try linking with -N
    strip:debian/packagename/usr/share/python/packagename/lib/python3.4/site-packages/sklearn/linear_model/stSBnUjs[.note.gnu.build-id]: Bad value
    BFD: debian/packagename/usr/share/python/packagename/lib/python3.4/site-packages/sklearn/linear_model/stSBnUjs: Not enough room for program headers, try linking with -N
    strip:debian/packagename/usr/share/python/packagename/lib/python3.4/site-packages/sklearn/linear_model/stSBnUjs: Bad value
    dh_strip: strip --remove-section=.comment --remove-section=.note --strip-unneeded debian/packagename/usr/share/python/packagename/lib/python3.4/site-packages/sklearn/linear_model/sgd_fast.cpython-34m.so returned exit code 1
    make: *** [binary] Error 29
    dpkg-buildpackage: error: debian/rules binary gave error exit status 2


 I am not sure how to resolve this. I'll be trying a bit more - feedback appreciated. 

 As a comment, I had to make several adjustments to get to that. I was trying out with different versions of the package to avoid certain errors that only occur with some of the flags. So I had to use the deb package based on github and uninstall other pip installed versions. 

 I first got this error: 
    [...]
    debian/rules clean
    dh clean --with systemd,python-virtualenv
    dh: unable to load addon systemd: Can't locate Debian/Debhelper/Sequence/systemd.pm in @INC (you may need to install the Debian::Debhelper::Sequence::systemd module) (@INC contains: /etc/perl /usr/local
    /lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at (eval 13) line 2.
    BEGIN failed--compilation aborted at (eval 13) line 2.

But installing a new package fixed it: 
    sudo apt-get install dh-systemd


Cheers!

**Comment by jhermann** [comment]
If you use dh-systemd in your rules, then that must be part of your build-depends.

**Comment by benman1** [comment]
I've put it in, but it doesn't change anything.

**Comment by nailor** [comment]
Hi,

sounds like you have been hit by issue #150. There are some solutions in there that might work for installing packages like sklearn.

**Comment by jhermann** [comment]
Current thread is #203, closing this.
