### ISSUE TITLE
Any interest in supporting python3

### ISSUE THREAD

**Issue by asottile** [spotify/dh-virtualenv#172]
The codebase is pretty small and I could make it happen.

**Comment by nailor** [comment]
What do you mean by Python 3 support? The nin-buildsystem part already
supports it (just pass in python3 as interpreter)

**Comment by asottile** [comment]
Currently the python bits of dh_virtualenv require a python2 interpreter:
- https://github.com/spotify/dh-virtualenv/blob/403bb44d3dd86615428ca02c82de44b4b3ea1de9/tox.ini#L2
- https://github.com/spotify/dh-virtualenv/blob/403bb44d3dd86615428ca02c82de44b4b3ea1de9/debian/control#L5

In modern debian systems, only python3 is shipped by default

**Comment by nailor** [comment]
Ah, good point. Thought you meant packaging Python 3 software with dh-virtualenv!

The reason it uses Python 2 now is that the `debpython`, which ships with the Debian and Ubuntu installations, is in Python 2 (or, well, at least has been). It is used [here](https://github.com/spotify/dh-virtualenv/blob/403bb44d3dd86615428ca02c82de44b4b3ea1de9/bin/dh_virtualenv#L29). 

If those are identical enough, then why not, but testing might become a bit cumbersome, as the actual build part is not tested apart manual runs (also something to be fixed, into the long TODO list you go...)

**Comment by asottile** [comment]
Ah right, didn't notice the debpython dependency.  From a cursory look I'm not locating that on my xenial instance so perhaps this isn't worth doing.

**Comment by nailor** [comment]
I'm guessing that the debpython will become Python 3 at some point (it's not anything complicated either). On the other hand, since that is only used by dh-python (and, duh, dh-virtualenv), maybe there's no pressure to change.

**Comment by asottile** [comment]
I wonder if dh-virtualenv could vendor the file (that might in fact eliminate some of the wackiness with squeeze I saw in the comments)?

**Comment by nailor** [comment]
Maybe, but that would need some licensing clearance (which is not a biggie, just something to me to clear).  However, I prefer avoiding vendoring until a really good reason comes up :)
 
Squeeze mentions are probably something that could be nuked (as well potential special code), as not even us (Spotify) are running that anymore, and I hope not many others either.. :D
