### ISSUE TITLE
Using dh-virtualenv without having to install it?

### ISSUE THREAD

**Issue by bbrcan** [spotify/dh-virtualenv#173]
Hi all!

I won't bore you with all the details, but basically I'm constrained in a build environment with no root access. Debhelper _is_ installed, but dh-virtualenv isn't.

It seems that in order to use dh-virtualenv with debhelper (for example, `dh $@ --with python-virtualenv`), the appropriate files need to be installed in:
- `/usr/share/perl5/Debian/Debhelper/Sequence/`
- `/usr/share/perl5/Debian/Debhelper/Buildsystem/`

My question is (and I apologise as I have zero experience with either debhelper _or_ Perl): Is there any way to use dh-virtualenv with debhelper, without having to install it? So for example, have debhelper use a copy of dh-virtualenv in my home directory?

(As a last resort I can just create my own local debhelper instance with dh-virtualenv installed into it, but I was hoping to avoid having extra dependencies/build steps)

Thanks a lot! :)

Ben

**Comment by jhermann** [comment]
These days, a Vagrant box / docker image is the usual solution to such conditions.

**Comment by bbrcan** [comment]
Thanks for your response, jhermann!

Absolutely! Unfortunately, the environment I am working in doesn't have Docker or anything similar installed. It's Ubuntu 12, and pretty bare-bones.

For a bit of background: basically where I work we have a custom build/release system. If you want to release a package, it must be built on a special 'build machine'.

We traditionally do C/C++ stuff so our build system has zero support for Python. I am trying to get around this by writing some scripts that the build system can execute, that will bundle up our new and awesome Python scripts into debian packages using dh-virtualenv. :)

**Comment by jhermann** [comment]
I understand your problem, but let's be realistic: there are way more sensible solutions, and pretty much nobody will provide a solution to problems caused by previous-century enterprise rules.

What you *can* try is put a virtualenv in the build user's homedir and then link its bin/dh_virtualenv into ~/bin.
