### ISSUE TITLE
pip can't install package from git

### ISSUE THREAD

**Issue by lulouie** [spotify/dh-virtualenv#177]
I have a package in requirements.txt base from git,
e.g. `git+https://github.com/foo/bar#egg=foobar`

but when using dh, it seems not using git but from pypi.

Is that a problem from dh, or from make-deb?

Thanks!

**Comment by jhermann** [comment]
Make sure you --preinstall a current pip. And this possibly requires the --pre flag, after all you package unreleased software.

**Comment by nailor** [comment]
I'm closing this issue, let us know if the workaround does not work
