### ISSUE TITLE
Solve version number update in a neat way

### ISSUE THREAD

**Issue by nailor** [spotify/dh-virtualenv#178]
Currently the version number is in place in four places:
- `debian/changelog`
- `doc/conf.py`
- `dh_virtualenv/cmdline.py`
- `setup.py`

It would be quite sweet if these could be sourced from one location. Unfortunately the `debian/changelog` can't be programmatically created, unless involving makefiles etc, and having that as the authoritative location would mean we would need to package it with the Python package. Though, to be honest, not sure if python packaging of this is really any concern.

**Comment by moleman** [comment]
For the python package version, one approach would be to use https://github.com/pypa/setuptools_scm/ that will use scm tags as a authoritative location of version numbers. I'm using that for my own projects and it's working great. You can specify it to write the version number to a file that you can import.

When it comes to the debian/changelog I guess you could write a a script to add a new entry by using the version number from the version file.

**Comment by jhermann** [comment]
> Unfortunately the debian/changelog can't be programmatically read…

    debianized-devpi$ dpkg-parsechangelog | egrep ^Version
    Version: 3.0.2-2~trusty

**Comment by nailor** [comment]
@jhermann Whoops, was going to write can't be programmatically created :)

**Comment by nailor** [comment]
@jhermann Though I'm pretty sure the dpkg-parsechangelog or a poor man's ripoff off that in the Python code would get the job done quite easily. No-one expects this package to be available in PYPI anyway

**Comment by jhermann** [comment]
https://github.com/1and1/debianized-sentry/blob/master/setup.py#L40 shows how to read pretty much all relevant Debian metadata from Python.

**Comment by nailor** [comment]
Nice! In a vacation now but will look into this when back, thanks!

**Comment by jhermann** [comment]
Sphinx conf done in f93e148
