### ISSUE TITLE
Suitable for Beaglebone?

### ISSUE THREAD

**Issue by MrBillium** [spotify/dh-virtualenv#179]
Will dh-virtualenv work well on a Beaglebone where storage (4GB) and horsepower are limited? 
Uninterrupted access to Hardware resources - GPIO's etc is a must too.
Some virtual environments can have trouble with hardware and performance.

Opinions?

Thanks

Bill

**Comment by jhermann** [comment]
There is an easy answer: just try it.

**Comment by nailor** [comment]
Yup, I agree, just try it. Note that this is not a virtualisation solution like KVM or others, but quite slim wrapper around Python to (simplified put) fix PYTHONPATH :)

Closing the issue, hope it works on your beagleboard!
