### ISSUE TITLE
unknown substitution variable ${python:Depends}

### ISSUE THREAD

**Issue by nicktime** [spotify/dh-virtualenv#181]
Hi, I've adapted my deb package by following the tutorial.
When building package I get:
> dpkg-gencontrol: warning: Depends field of package tcptee: unknown substitution variable ${python:Depends}

And my 
> Depends: ${python:Depends}, ${misc:Depends}

turns into a
> Depends: sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16)

Whereas when I built the package before (without dh-virtualenv) I got it converted into
> Depends: python (>= 2.7), python (<< 2.8), python:any (>= 2.7.1-0ubuntu2), python-pkg-resources, python-tz, python-gevent, sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16)

Looks like an issue with ${python:Depends} not being defined.

**Comment by nailor** [comment]
Yeah, it is not. Should probably clean the docs for that. Thanks for catching!
