### ISSUE TITLE
Global symbol "$curdir" requires explicit package name

### ISSUE THREAD

**Issue by mgagne** [spotify/dh-virtualenv#185]
Using latest revision from master (139c95a865c286f0c4e118d12653740cfc1b9da1), I'm getting this error:

```
dh_auto_clean
dh_auto_clean: unable to load build system class 'dh_virtualenv': Global symbol "$curdir" requires explicit package name at /usr/share/perl5/Debian/Debhelper/Buildsystem/dh_virtualenv.pm line 153.
Compilation failed in require at (eval 4) line 2.
BEGIN failed--compilation aborted at (eval 4) line 2.

make[1]: *** [override_dh_auto_clean] Error 255
make[1]: Leaving directory `/build/build-area'
make: *** [clean] Error 2
```

I think the regression was introduced by this commit: c2b113a30ae50824767bbfdd3c83854ad47ab607

**Comment by dzen** [comment]
Yes it does. I really appologies for the inconvenience :(

@nailor Is there a way to enable a perl linter on travis ?

**Comment by nailor** [comment]
Probably there is! I can look into that

**Comment by nailor** [comment]
Looks like it is some stretch to get it done on Travis level. I'll open separate issue for this to figure out workaround https://github.com/travis-ci/travis-ci/issues/4090
