### ISSUE TITLE
Cannot import modules from editable pip dependencies

### ISSUE THREAD

**Issue by anka-sirota** [spotify/dh-virtualenv#189]
Hi! I have a package that has editable dependencies which seem to build and install correctly, but are not available inside the resulting venv after the package is installed.
Looking closely into the site-packages, I see the `.egg-link`s files for those editable modules, and they all look like this:

```
/build/<package>/debian/<package>/opt/venvs/<package>/src/<module>
.
```
`dh_virtualenv` reports version 0.11

Also, `site-packages/easy-install.pth` contains build-related paths as well:

```
import sys; sys.__plen = len(sys.path)
./distribute-0.6.24-py2.7.egg
./pip-1.1-py2.7.egg
/build/<package>/debian/<package>/opt/venvs/<package>/src/<module>
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
```

Maybe I'm missing some configuration option here
Is there any way to fix this and make editable deps work?

**Comment by anka-sirota** [comment]
looks like a duplicate of https://github.com/spotify/dh-virtualenv/issues/134, sorry about that

**Comment by nailor** [comment]
No prob, good to know there are more people in need of this :)

I'll close this bug as a duplicate, but please feel free to re-open in case you don't agree!
