### ISSUE TITLE
cannot write to /root/.ssh

### ISSUE THREAD

**Issue by mgwilliams** [spotify/dh-virtualenv#19]
When running dpkg-buildpackage (as an unprivileged user) with git+ssh URLs in `requirements.txt`, the following error is generated:

`Could not create directory '/root/.ssh'.`

pip should be using the user's .ssh directory, not root's.

**version info:**
dh-virtualenv: 0.6
python: 2.7
pip: 1.0
setuptools: 2.0.1

**Comment by rmariano** [comment]
Hello, I tried the approach suggested by @mgwilliams and while it seems promising, I did not work, could I have more details on it? In addition, do you know of another workaround?
I tried several things, even changing the `known_hosts` file, setting the ssh config (`~/.ssh/config`) in order not to check the hosts, etc. and it is still failing with the avobe issue (it tries to write into `/root/.ssh/known_hosts`).

Thanks in advance!

**Comment by mgwilliams** [comment]
@rmariano Here's an excerpt from my working Makefile:

```make
deb:
	mkdir -p tmp
	echo '#!/bin/sh\nssh -oUserKnownHostsFile=$(HOME)/.ssh/known_hosts $$@' > tmp/ssh_wrapper && chmod +x tmp/ssh_wrapper
	GIT_SSH=$(CURDIR)/tmp/ssh_wrapper dpkg-buildpackage -b
```

**Comment by jhermann** [comment]
Just use git+https instead and avoid the whole problem, instead of hacking around it.

**Comment by chrispbailey** [comment]
Just to confirm @rmariano's solution works for me (using the `dh` command not `dpkg-buildpackage`):

```
%:
	mkdir -p tmp
	echo '#!/bin/sh\nssh -oUserKnownHostsFile=$(HOME)/.ssh/known_hosts $$@' > tmp/ssh_wrapper && chmod +x tmp/ssh_wrapper
	GIT_SSH=tmp/ssh_wrapper dh $@ --with python-virtualenv
```
