### ISSUE TITLE
v1.0 – more info

### ISSUE THREAD

**Issue by adi-** [spotify/dh-virtualenv#193]
Backwards incompatible Buildsystem: Move files into build folder in install step instead of build step. Thanks to Ludwig Hähne for the patch!

Could you be more specific and write more about this feature in the docs? Some examples etc. I hope this enables us to just copy packages from local disk rather than install them. Am I right?

**Comment by adi-** [comment]
I guess the code responsible for moving libs (and not copying them) hasn't hit the 1.0 release. The patch by Ludwig Hähne doesn't seem to be present in the final 1.0 – functionality is only mentioned in the docs.

**Comment by adi-** [comment]
This commit exactly:
https://github.com/Pankrat/dh-virtualenv/commit/3fcc4bb05a9202b5cff3f4a63f6e56926dd9ede8

**Comment by nailor** [comment]
Change in question is fc88145

This does not change much how the packaging works (install is done in a later step in the chain). If something breaks it might be builds that use the experimental build system and have completely overridden install step. Breakage will be obvious though.

I don’t see any need for extra documentation for this particular feature. Thanks for asking clarification though and sorry that the answer took a while!
