### ISSUE TITLE
Docs: Mention some canonical GitHub topics?

### ISSUE THREAD

**Issue by jhermann** [spotify/dh-virtualenv#199]
I use the following topics for my dh-virtualenv projects:

debian-packages dh-virtualenv deployment omnibus-packages 

Maybe we can agree on a list, and add a hint to the docs. That'd make finding already packaged applications a lot easier – [at least on GitHub](https://github.com/search?q=topic%3Adh-virtualenv&type=Repositories).

PS: This project has no topics yet. :wink:

**Comment by nailor** [comment]
Done! 

Hadn't even noticed the whole topics feature :)
