### ISSUE TITLE
Use --ignore-installed flag

### ISSUE THREAD

**Issue by awelkie** [spotify/dh-virtualenv#206]
I just ran into an issue where a package in my `requirements.txt` wasn't installed in the virtualenv because I was using `--system-site-packages` and the package was installed globally on my build machine.

It seems to me that the pip option `--ignore-installed` should always be used, or at the very least there should be a way of enabling it (like the `--system-site-packages` flag).

**Comment by jhermann** [comment]
That is what ``--extra-pip-arg`` is for, any reason you cannot use it here?

**Comment by awelkie** [comment]
Ah, I didn't see that option. Yes, that looks like it'll do what I want.
