### ISSUE TITLE
Tests are run by default

### ISSUE THREAD

**Issue by bochecha** [spotify/dh-virtualenv#209]
The documentation says that tests aren't run by default any more since 1.0

I'm using dh-virtualenv 1.0, and here's my `debian/rules` file:

```make
#!/usr/bin/make -f

export DH_VERBOSE=1
export DH_VIRTUALENV_ARGUMENTS=--python=/usr/bin/python3
export DH_UPGRADE_SETUPTOOLS=
export DH_PIP_EXTRA_ARGS=--no-use-wheel

%:
	dh $@ --with python3 --buildsystem dh_virtualenv
```

Yet, when building, I see this in the output:

```
   dh_auto_test -O--buildsystem=dh_virtualenv
	/builds/ideascube/ideascube/build/usr/share/python/ideascube/bin/python3 setup.py test
```

I tried adding the following to the `debian/rules` file:

```make
override_dh_auto_test:
	:
```

And indeed, now, the tests aren't run any more.

So at least I have a pretty trivial work-around, but it would be nice if the behaviour matched the documentation.

**Comment by nailor** [comment]
Use of `--with python3` probably triggers `dh_python` build pipelines and that causes the system to run tests.

**Comment by bochecha** [comment]
So dh-virtualenv shouldn't have the same behaviour with python2 and python3? 😕

**Comment by nailor** [comment]
Clarified my comment above a bit, but if you say `--with python2` (or python3) that means that Debhelper will pick `dh_python2` (or respectively 3) sequencer to run. That will execute override_dh_auto_test, which the buildsystem is not removing. 

You could run `--with python-virtualenv` which does not run the experimental buildsystem but a more "traditional" sequencer, and that skips testing.

**Comment by bochecha** [comment]
Yeah, we were using `--with python-virtualenv` before, and that didn't run the tests indeed.

> Another thing is that the default running of tests is about the non-experimental version of dh-virtualenv, buildsystem most likely sitll runs them and override you did is the way to go.

Ok, that was definitely not obvious from reading the documentation.
