### ISSUE TITLE
python,orig file is not removed from ${VIRTUALENV}/bin/

### ISSUE THREAD

**Issue by lez** [spotify/dh-virtualenv#214]
When the system interpreter differs from the one in the deb package, the postinst script (added by dh_virtualenv) overwrites the virtualenv interpreter to the system version. The original interpreter is kept under the name `python,orig`.

I'm not sure if this file is supposed to stay there as a backup and removed by the package's prerm script, or it can already be removed already in postinst script. Either in postinst or prerm, I'm happy to write the patch that removes this file automatically.

**Comment by jhermann** [comment]
``prerm`` would be the proper place. A PR would be great.
