### ISSUE TITLE
dh-virtualenv not pickign up env var DH_PIP_EXTRA_ARGS

### ISSUE THREAD

**Issue by gustavooferreira** [spotify/dh-virtualenv#215]
Hi,

I'm using dh-virtualenv 1.0, and if I use the command line option:

> --extra-pip-arg "--proxy=https://127.0.0.1:8888"

It works fine and all traffic goes via the proxy, but if I use the env variable instead:

> export DH_PIP_EXTRA_ARGS="--proxy=https://127.0.0.1:8888"

dh-virtualenv doesn't pick on this.

I actually prefer to use the env var, could you guys have a look?

Thanks!

**Comment by jhermann** [comment]
Where did you find docs that indicate to swap "pip" and "extra"?

**Comment by gustavooferreira** [comment]
Hi,

So, for the command line option, it's here:
http://dh-virtualenv.readthedocs.io/en/latest/usage.html#cmdoption-extra-pip-arg

For the environment cariable, it's here:
http://dh-virtualenv.readthedocs.io/en/latest/usage.html#envvar-DH_PIP_EXTRA_ARGS


My guess is that dh-virtualenv isn't picking up the environmnet variable and as a consequence it doesn't set the proxy.

**Comment by jhermann** [comment]
Look at the title of the second linked section and you know why it is not picked up. 

Still the var name is inconsistent to the option.

**Comment by gustavooferreira** [comment]
Oh, I see, you are right.

My bad. It's working now. Closing the issue.
