### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gustavooferreira** [spotify/dh-virtualenv#216]
Hi, is it possible to make a new release?

The env var DH_VIRTUALENV_INSTALL_SUFFIX is newer than the latest release and I can't use it yet.

If you guys could release a new version, that would be cool.

Thanks.

**Comment by gustavooferreira** [comment]
Especially because this env var has been added more than half a year ago.

Thanks.

**Comment by nailor** [comment]
Hi!

Yeah, a new release would definitely be in place. I’m on a parental leave atm but I’ll try pushing it through at some point when I get my hands on all the signing keys!

**Comment by gustavooferreira** [comment]
Oh ok, congratulations then!

**Comment by jhermann** [comment]
@nailor Parental leave over? (or your laws are *really really* generous) :smiley_cat: 

I'm missing the pip upgrade fix, just bit me on Jessie again, have to build git head…

**Comment by jhermann** [comment]
@nailor Everything's prepped for relase v1.1, please…

* merge https://github.com/spotify/dh-virtualenv/pull/245
* merge https://github.com/spotify/dh-virtualenv/pull/250
* follow "Releasing a new version" step 4+ in the new README

**Comment by nailor** [comment]
Nice, thanks! On vacation but will do a release when back (Sept 17). Sorry
for this dragging

**Comment by jhermann** [comment]
Ping @nailor – sorry for being a pain in the neck, but can you give us an estimate when you'll come around to it?

**Comment by nailor** [comment]
Back from vacation now! Expect this to be done by end of day Monday (24th)!

- Jyrki

**Comment by nailor** [comment]
1.1 was uploaded to Debian yesterday!
