### ISSUE TITLE
dh-virtualenv does not fix shebangs by the latest pip/distlib

### ISSUE THREAD

**Issue by ghost** [spotify/dh-virtualenv#225]
With the latest pip, on "posix" systems, with shebang paths longer than 127 characters, pip generates a multiline shebang. dh-virtualenv is not aware of such paths and they keep their build-time value.

New shebang style example:
```
#!/bin/sh
'''exec' /build/ourpackage/debian/ourpackage-venv3/opt/venvs/ourpackage-venv3/bin/python "$0" "$@"
' '''

```

**Comment by jhermann** [comment]
Should be fixed before 30 Apr – the pypi.org final switch date which implies using a recent pip.

**Comment by nailor** [comment]
Thanks for flagging this! Do you happen to have a pointer to relevant parts of distlib/pip where this happens? I'd like to dig a bit and understand more

**Comment by jbfzs** [comment]
Right here: https://github.com/pypa/pip/blob/0007825733aa862e76a66e5d1cfee121c29192ff/src/pip/_vendor/distlib/scripts.py#L139

It took me a while to find out what was causing this in the first place.

**Comment by nailor** [comment]
Thanks!

By the way, have to say this is a pretty damn neat hack on pip-side! Took a moment to grasp for me, but basically the flow is:

1. Count how long shebang is.
2. If less than limit (Linux limit 127), use the old style. If longer, cook up new one
3. Use `/bin/sh` as shebang. Make first 'executable' line the `'''exec' ....`

Now when executing the script with the long shebang, it'll be executed by your regular interpreter. Quotes don't matter (this took while for me to figure out), as the two first single quotes are just empty string (you can try this by executing `''ls` in your terminal). The third single quote just quotes the exec (as you can see there's quote after that too). Also doesn't matter: try `'''ls'`. Then it just calls Python with first argument being `$0`, i.e. the script itself, followed by positional arguments passed in. Next line is just first single quotes, i.e. does not matter at all for sh.

This leads it to executing the same script again with the virtualenv's python interpreter, except this time the exec statement is actually just a random string in triple quotes and thus skipped! Mind. Blown.

![clapping](https://media.giphy.com/media/d5KuLHHTSaRnG/giphy.gif)

**Comment by nailor** [comment]
Side note: This trick would be neat to replicate in dh-virtualenv if we detect too long shebangs!

**Comment by nailor** [comment]
I added an initial PR, which still needs some test builds, to fix these shebangs

**Comment by jbfzs** [comment]
@nailor Your pull request works correctly and produces corrected shebangs in my setup.

Thanks !

**Comment by nailor** [comment]
This is now fixed in the master, closing the ticket
