### ISSUE TITLE
Getting my project entry points on path using dh_virtualenv

### ISSUE THREAD

**Issue by Karhide** [spotify/dh-virtualenv#227]
Hi there,

So let’s say I have a python project that has some entry points defined in setup.py. Normally during installation these would end up on the path, but obviously if we are installing inside a virtualenv we would have to activate it first, which is no problem normally but if you are shipping software (my reason for debianising it in the first place) it would be normal for a user to be able to use it globally.

I was just wondering, therefore, what would be the best way to make dh_virtualenv built packages accessible. Simplest way I can imagine is just a postinst script that moves the relevant entry points to somewhere on the path. But you guys must have encountered this and have a preferred way of doing it, so here I am!

Thanks.

**Comment by jhermann** [comment]
https://github.com/1and1/debianized-sentry/blob/master/debian/sentry.io.links

**Comment by Karhide** [comment]
Perfect!

**Comment by jhermann** [comment]
@nailor working on https://github.com/jhermann/dh-virtualenv/issues/1 now, since I shuffle things around, please do not touch doc/ this weekend.

**Comment by jhermann** [comment]
Can be closed → https://github.com/spotify/dh-virtualenv/pull/237
