### ISSUE TITLE
Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by bee-mere** [spotify/dh-virtualenv#248]
Hi,

I wanted to try this promising tool today (thank you for sharing it!), but when I try to run `dpkg-buildpackage -us -uc`, it fails giving the error

````
...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-8gc4zhap/
...
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
````

I found issue #232 where someone had a similar problem. A suggestion was to check the output of running `python setup.py` egg_info directly. This also fails:

````
$ python setup.py egg_info
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'egg_info'
````

Googling for this issue (e.g. [here](https://stackoverflow.com/questions/11425106/python-pip-install-fails-invalid-command-egg-info)), I found that a common suggestion is that `setuptools` is not up-to-date. But even after running `pip install --upgrade setuptools`, retrying the above fails.

I would be greatful for any hint on how to solve this issue. Thanks in advance.

On my system:
`uname -a` gives `Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`
`python -V` is 2.7.13 
`pip -V` is 9.0.1
and `pip show setuptools` produces
````
Name: setuptools
Version: 40.2.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /home/julian/.local/lib/python2.7/site-packages
Requires:
````

**Comment by jhermann** [comment]
Link to your setup.py / git repo?

**Comment by bee-mere** [comment]
I had a wrong configuration in my setup.py. Sorry for bothering you about this.
