### ISSUE TITLE
using dh-virtualenv with cython code

### ISSUE THREAD

**Issue by ramezquitao** [spotify/dh-virtualenv#262]
I'm trying to use dh-virtualenv with come code that includes modules in cython, but I'm getting errors of the type:

```
File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 108, in nonempty
    raise ValueError(error_msg)
ValueError: 'debian/my-compiler/opt/venvs/my-compiler/include/python2/7/mpi4py/__init__.pyx' doesn't match any files
```

Is there any example on how to use  dh-virtualenv with modules written in cython?

Thanks

**Comment by jhermann** [comment]
Get an error when, based on what command? Where is your project?

Anyway, try to build a wheel for your platform *outside* of packaging, and make it available (install devpi, or add a local dir as index URL in `rules`).

**Comment by ramezquitao** [comment]
Dear Jürgen, the error appears when running the  "dpkg-buildpackage -us -uc"
command.  Before the error message the command that appears to be running
is "python setup.py egg_info" . I tried running by hand this command and
the same error appeared. Still I will try your suggestion, thanks.

**Comment by ramezquitao** [comment]
I found that I was making a mistake. My project was using distutils instead setuptools. I haven't been able to create the virtual enviroment, but the problem is different now. 

Until I understand better what is going on, I think this issue can be closed.

Thanks for the help

**Comment by ramezquitao** [comment]
I did found the error. My setup.py is scanning the source tree to find the .pyx files used to create the extensions. This process was also finding the pxy files inside the the virtualenv directory created inside the debian directory (burried inside). All I had to do was to exclude those files.

**Comment by msmyers** [comment]
> I did found the error. My setup.py is scanning the source tree to find the .pyx files used to create the extensions. This process was also finding the pxy files inside the the virtualenv directory created inside the debian directory (burried inside). All I had to do was to exclude those files.

How did you exclude it?
