### ISSUE TITLE
Sequence "dh_virtualenv" waits for input from stdin

### ISSUE THREAD

**Issue by sumpfralle** [spotify/dh-virtualenv#264]
The following block [dh_virtualenv.pm#L162](https://github.com/spotify/dh-virtualenv/blob/master/lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm#L162) causes the build process to wait for input from stdin:

```perl
local $^I = q{};
local @ARGV = grep { -T } @binaries;
while ( <> ) {
    s|^#!.*bin/(env )?python|#!$new_python|;
    print;
}
```

For me this happens while `@ARGV` is empty.

Workarounds:
* interactively: press `CTRL-D` while it is waiting
* non-interactively: redirect stdin to `/dev/null` for the build process

**Comment by nailor** [comment]
Buildsystem parts are a bit unsupported, so closing this issue. 

From top of my head it could fail if there are no binaries, but that also makes the built package bit odd.
