### ISSUE TITLE
Qustion: using getpip or similar to get a specific pip version?

### ISSUE THREAD

**Issue by forslund** [spotify/dh-virtualenv#266]
Is there any way to use a service like getpip to install the preferred pip version?

Background:
we use the extra pip flag `--no-cache-dir` on a debian Jessie machine. The pip version that get's installed doesn't support this flag. To get this to work we've been using `--upgrade-pip` to get us to a python which supports this option.

This is sort of bad since we're always going to end up on the latest pip at some stage during the setup. Today that bit us since the `--no-cache-dir` option broke when pip 19.0.0 was released. And using `--preinstall` to install an older version of pip wouldn't work either since the preinstall command also gets passed the `--no-cache-dir` option.

The --no-cache-dir issue has been resolved upstream from pip==19.0.1 but we're running python 3.4 on our target and pip will not support python 3.4 beyond 19.1 so we'll need to freeze our pip version before then.

The only way I can think of from the top of my head is to create a shell script wrapping the pip call stripping failing arguments if the version is too low...

**Comment by nailor** [comment]
Yeah, we have had an unfortunate fallout from that pip upgrade too 🙁

Unfortunately I don’t know if there is any neat way for current release of dh-virtualenv to do this.

This [ticket](https://github.com/pypa/pip/issues/6158) offers disabling the asserts via environmental variable which might be feasible (not entirely sure what variables get passed through  in build env)

Proper fix for dh-virtualenv would be to allow passing argument to `—upgrade-pip` which would be the desired version, and if not passed, pull the newest one

**Comment by forslund** [comment]
That would be an excellent solution

**Comment by jhermann** [comment]
Working on this, PR coming up
