### ISSUE TITLE
Build of Java-based dependency using dh_virtualenv tries to write to /root

### ISSUE THREAD

**Issue by ShaheedHaque** [spotify/dh-virtualenv#269]
I am trying to package project with dh_virtualenv so I can track the non-Python dependencies as well as the Python dependencies (in setup.py). This is mostly working nicely, but I'm having trouble one Java-based dependency: [a github/PyPI project](https://github.com/bcdev/jpy):

- This needs a JAVA_HOME to be set because it contains JAVA code.
- This needs a pointer to the github repo because the PyPI version is too old to use.

Note that I can make everything work using pip directly like this:

```
$ JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 pip3 install --upgrade 'https://github.com/bcdev/jpy/tarball/ae813df5368' 
Collecting https://github.com/bcdev/jpy/tarball/ae813df5368
  Downloading https://github.com/bcdev/jpy/tarball/ae813df5368
     - 1.6MB 8.2MB/s
Installing collected packages: jpy
  Running setup.py install for jpy ... done
Successfully installed jpy-0.10.0.dev1
```
Notice the form of the URL is simply "http://..." rather than the "jpy@http://..." that [recent developments would suggest](https://www.python.org/dev/peps/pep-0508/). I *think* that is because Ubuntu 18.10 comes with pip3 9.0.1 which seems ancient (I tried to upgrade it but had trouble doing so). 

When I add the entry to install_requires and run dh_virtualenv, it seems that the "jpy@http://..." format is enforced, but even with that in place:
```
    install_requires=[
        ...,
        'jpy@https://github.com/bcdev/jpy/tarball/ae813df5368',
    ]
```
and the environment variable set in the debian/rules file:
```
override_dh_virtualenv:
	JAVA_HOME=$(JAVA_HOME) dh_virtualenv --pip-tool=pip3 --setuptools
```
the build fails. If I run with DH_VERBOSE=1, I see that the build succeeds for a load of C code and then I see this error:
```
  x86_64-linux-gnu-gcc  ...
  ...lots of stuff...
  x86_64-linux-gnu-gcc ...
  installing to build/bdist.linux-x86_64/wheel
  running install
  running maven
  Executing Maven goal 'package'
  WARNING: An illegal reflective access operation has occurred
  WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
  WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
  WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
  WARNING: All illegal access operations will be denied in a future release
  [ERROR] Could not create local repository at /root/.m2/repository -> [Help 1]
  [ERROR]
  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
  [ERROR]
  [ERROR] For more information about the errors and possible solutions, please read the following articles:
  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
error
  Failed building wheel for jpy
```
Note that the path it is writing to is /root/..., whereas I am running all this as a vanilla user. What does dh_virtualenv do that causes us to end up pointing to /root?

**Comment by jhermann** [comment]
It uses fakeroot. Set M2_REPO. DO upgrade pip, there is no way around that. But do not upgrade to 19.x (i.e. use the HEAD of dh-venv, see latest commits). Do not use Java11, use Java8. And "…#egg=jpy" in your links.

**Comment by ShaheedHaque** [comment]
Never mind. I hacked around things to get a complete venv, only to realise that a binary wheel built on Ubuntu 18.10 was not going to work on an LTS Ubuntu 18.04...
