### ISSUE TITLE
/opt/venvs/ path not amenable to apt-get purge command

### ISSUE THREAD

**Issue by rschwiebert** [spotify/dh-virtualenv#280]
I have a question on if I'm doing something right or not.

When trying to purge my package:

`Removing thepackage (0.0.1) ...
Purging configuration files for thepackage (0.0.1) ...
dpkg: warning: while removing thepackage, directory '/opt/venvs/thepackage/lib/python2.7/site-packages/pkg_resources/extern' not empty so not removed`

I was hoping that would sorta just work... but then again, I might not be aware of some debian script thing I should be doing to facilitate the cleanup of these files.  If there is, could you let me know? Thanks.

**Comment by marcvs** [comment]
I've hit the same issue, I'll file a PR that fixed that for me.

**Comment by nailor** [comment]
Hi, and sorry for a late comment!

Do we foresee issues with force removal? My gut sets no, but force removal flag is always a bit dangerous

**Comment by jhermann** [comment]
Well, these are Python packages that store dynamic data into their `__path__`, and they shouldn't.

I'd say the proper fix is docs -- show how to remove what *your* selection of 3rd party packages leaves behind in those paths (using some well-known example), and remove the trash in a `prerm` or `postrm`.

cf. https://github.com/1and1/debianized-jupyterhub/blob/master/debian/postrm#L25

**Comment by nailor** [comment]
Thanks @jhermann , indeed sounds like a sane strategy. I’ll close this issue for now, as indeed the prerm and postrm are the places to do this
