### ISSUE TITLE
Question: Using custom built python

### ISSUE THREAD

**Issue by forslund** [spotify/dh-virtualenv#283]
We're running on some devices where python.3.4 is the system python. We're currently using dh_virtualenv which has been working great but now I'm looking into upgrading to python3.7.

On my test platform I've installed python3.7 from source and switched the python executable to use. At the end I run into an issue where the libpythonm.so.1.0 dependency can't be determined by dh_makeshlibs (since it's not installed as a debian package) is there a way to manually include this so-file into the debian package?

Or do I need to package python3.7 separately and add it as a dependency?

**Comment by forslund** [comment]
Answering myself: adding the lib to the install file passes this stage and the package is created. Now to see if this is enough to get it working 100%

**Comment by jhermann** [comment]
If you're on Ubuntu, use the deadsnakes PPA.

**Comment by forslund** [comment]
I'm on debian Jessie on the Pi, but I'll see if the xenial repo's version is close enough...

Otherwise I need to find / package it myself it seems.

**Comment by forslund** [comment]
Question answered, closing issue.
