### ISSUE TITLE
Using a package name like python3-mypackage results in an empty package

### ISSUE THREAD

**Issue by rschwiebert** [spotify/dh-virtualenv#285]
I had a package building with dh_virtualenv... until today.

I didn't change anything in the debian packaging, but I am aware that I was adding packages allowing me to build different packages with pybuild on the same machine so possibly something was disturbed.

As per the docs in the cookbook I have the specified Build-depdends:

```
Build-Depends: cdbs, debhelper (>= 9), python3 (>=3.5), dh-virtualenv (>= 1.0),
               dh-systemd (>= 1.2), libpython3-dev, libsnappy-dev, python3-dev,
               python3-setuptools, python3-pip, libffi-dev, dh-python (>= 2.20151103ubuntu1)
```

And the specified pre-depends:
```
Pre-Depends: dpkg (>= 1.16.1), python3 (>= 3.5), ${misc:Pre-Depends}
```

and the rules file exports a few environment variables and then is just 

```
%:
	dh $@ --with python-virtualenv
```

~Nevertheless, the debhelper.log is totally devoid of any reference to python or virtualenv, and it just skips right from dh_perl to dh_link.~

When I try
```
%:
	dh $@ --with python-virtualenv -p packagename --python /usr/bin/python3
```
there is more debhelper activity, but it goes straight from dh_perl to dh_usrlocal

What to do?

**Comment by rschwiebert** [comment]
I finally stumbled across the thing that got it working again: I was trying to rename my package from python-mything to python3-mything, which I did in the setup.py, in the control file's `Package` field, and in the `rules` file call to dh, where I included it with the `-p` flag on `dh`.

Is there some proscription against that?

**Comment by jhermann** [comment]
I would discourage naming dh-venv stuff "python3-*" on principle – you use the naming convention for "normal" python packages for something which is not.

**Comment by nailor** [comment]
I'm open for wording in the docs, but I'm closing this issue as of now, since `python3-*` names should not be used for packages that are not libraries based on the "system python"
