### ISSUE TITLE
Adding non-package, system data files

### ISSUE THREAD

**Issue by robshep** [spotify/dh-virtualenv#299]
Hi,

I'm struggling to find where to place, or how to include system files.
For example I have this `<package>.install` file

    etc/mypkg.uwsgi.ini /etc/uwsgi/apps-enabled
    etc/default_config.json /var/lib/mypkg.default.json

However, the rules file sets the source directory to be: `debian/mypkg-$VERSION` and so these files are not picked up by `dh_install`

My layout is from using this: https://github.com/Springerle/dh-virtualenv-mold
which looks different to: https://github.com/1and1/debianized-sentry 
(I've tried to align with the latter without success)

As a debian packaging newbie, I cannot fathom how to hook into the build system to move files around.
Any pointers on how to get this going would be very appreciated. 

Thanks

**Comment by jhermann** [comment]
Provide a link to your repo, else this is reading tea leafs.

**Comment by robshep** [comment]
Sorry that’s not clear enough.
Well I have an internal package, so please let me make a test case.

In summary, I can’t find a way to include other files that must be installed as part of the package.  E.g. something for /etc

I’ll post a thinned test case.

Thanks


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robshep** [comment]
Small test case.
https://github.com/robshep/dhv-299
A reduced fileset from our internal package. 

Q. how to include `./etc/uwsgi.ini` into package as per `debian/dhv-299.install`

**Comment by jhermann** [comment]
well, your manifest does not include etc, so it is not copied via a source package.

**Comment by robshep** [comment]
Easy when you know how ;)
Thank you for the support.
R

**Comment by jhermann** [comment]
https://github.com/spotify/dh-virtualenv/blob/master/doc/howtos.rst takes PRs. 😉
