### ISSUE TITLE
dh: error: unable to load addon python-virtualenv

### ISSUE THREAD

**Issue by fredcox** [spotify/dh-virtualenv#308]
I have python3-virtualenv package installed

$ debuild
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: informação: pacote fonte crazydiskmark
dpkg-buildpackage: informação: versão da fonte 0.3.1
dpkg-buildpackage: informação: source distribution stable
dpkg-buildpackage: informação: fonte alterada por Fred Lins <fredcox@gmail.com>
 dpkg-source --before-build .
dpkg-buildpackage: informação: arquitetura do servidor amd64
 fakeroot debian/rules clean
dh clean --with python-virtualenv
dh: error: unable to load addon python-virtualenv: Can't locate Debian/Debhelper/Sequence/python_virtualenv.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python_virtualenv module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at (eval 12) line 1.
BEGIN failed--compilation aborted at (eval 12) line 1.

make: *** [debian/rules:4: clean] Erro 25
dpkg-buildpackage: erro: fakeroot debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed

**Comment by jhermann** [comment]
Use `--builtin-venv`, not virtualenv.
