### ISSUE TITLE
Question: Can build directory be identified in the rules file?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [spotify/dh-virtualenv#310]
Have been using `dh-virtualenv` for a while, works great, many thanks for making it available!

I am wondering whether this is possible at all. Given a `debian/rules` file with the contents

```
...
%:
	dh $@ --with python-virtualenv --sourcedir $(SDIST_DIR)

override_dh_virtualenv:
	dh_virtualenv $(DH_VENV_ARGS)
        ls ${WHERE_IS_PACKAGE_BUILT}
```

is it possible to access the build directory that `dh_virtualenv` operates on from the `rules` file? I'd like to do some post-processing after `dh_virtualenv` has finished its work. In the example above, how do I access the directory `WHERE_IS_PACKAGE_BUILT?` Is it something you expose explicitly using any environment variable?

**Comment by jhermann** [comment]
See https://github.com/1and1/debianized-jupyterhub/blob/22b677d2ffbdd12212e200244db4c86d5de093ef/debian/rules#L22

`$(CURDIR)` can also be helpful, which is the project root if your build setup is not severely broken, or `$(firstword $(MAKEFILE_LIST))`.

**Comment by alexey-tereshenkov-oxb** [comment]
Using a current directory works great, many thanks. 

I wasn't considering it to be a valid option at first because I thought that one can initiate building a package with`dpkg-buildpackage -uc -us -b` from an arbitrary location (that's how I used to do it with` fakeroot dpkg-deb --build package_build_dir deb_pkg_file_name`) and then current directory won't be the one where the `debian/rules` is located. 

So if I have my rules file in `/my/project/debian/rules` and run the `dpkg-buildpackage` command from `/some/other/dir` (passing the location of `/my/project` as an argument if that's possible at all) , the `$(CURDIR)` will show `/some/other/dir` unless I misunderstand something obvious.

**Comment by jhermann** [comment]
Well, being elsewhere is not what I do, so no experience with that here, but MAKEFILE_LIST hopefully contains abspaths -- just try it out.
