### ISSUE TITLE
Issue using Apt install for dh-virtualenv

### ISSUE THREAD

**Issue by georgeoffley** [spotify/dh-virtualenv#318]
I am trying to test out dh-virtualenv to determine if it is suitable for us to package our python software. I've been able to get all the helper utils to run, but when I run `apt install dh-virtualenv`, I get the following error:

`E: Unable to locate package dh-virtualenv`

I am running on Ubuntu 20.04.1 LTS x64 through a VM on my Windows 10 unit. I have also tried the other suggested install options, but I get the same results—each one reporting that an installation package could not be found.

**Comment by nailor** [comment]
Hi,

you should be able to install the package from [the PPA](https://launchpad.net/~jyrki-pulliainen/+archive/ubuntu/dh-virtualenv).

Note that the PPA is my personal one and might not receive updates as timely

**Comment by georgeoffley** [comment]
I actually tried this alternative as well and got similar results saying that there is no release candidate when trying the install. Here is the output that I get when running the PPA install:

`george@george-VirtualBox:~$ sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
[sudo] password for george: 
 Unofficial PPA for dh-virtualenv. Official releases are available on Debian Sid.
 More info: https://launchpad.net/~jyrki-pulliainen/+archive/ubuntu/dh-virtualenv
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:5 http://dl.google.com/linux/chrome/deb stable InRelease                   
Ign:6 http://ftp.debian.org/debian jessie-backports InRelease                  
Err:7 http://ftp.debian.org/debian jessie-backports Release              
  404  Not Found [IP: 151.101.118.132 80]
Get:8 http://ppa.launchpad.net/jyrki-pulliainen/dh-virtualenv/ubuntu focal InRelease [17.5 kB]
Ign:9 http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu focal InRelease
Err:10 http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Get:11 http://ppa.launchpad.net/jyrki-pulliainen/dh-virtualenv/ubuntu focal/main amd64 Packages [560 B]
Get:12 http://ppa.launchpad.net/jyrki-pulliainen/dh-virtualenv/ubuntu focal/main i386 Packages [560 B]
Get:13 http://ppa.launchpad.net/jyrki-pulliainen/dh-virtualenv/ubuntu focal/main Translation-en [256 B]
Reading package lists... Done                       
E: The repository 'http://ftp.debian.org/debian jessie-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
george@george-VirtualBox:~$ sudo apt-get update
Ign:1 http://ftp.debian.org/debian jessie-backports InRelease
Err:2 http://ftp.debian.org/debian jessie-backports Release
  404  Not Found [IP: 151.101.118.132 80]
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease   
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:7 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:8 http://ppa.launchpad.net/jyrki-pulliainen/dh-virtualenv/ubuntu focal InRelease
Ign:9 http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu focal InRelease
Err:10 http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu focal Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ftp.debian.org/debian jessie-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/spotify-jyrki/dh-virtualenv/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

Are there any other suggestions?

**Comment by jhermann** [comment]
Download the DEB file from sid, then `dpkg -i` it. Works everywhere not-to-ancient, and always the same.

**Comment by georgeoffley** [comment]
@jhermann hello I actually tried this today. When I go to `dpkg -i` the debian package I get a bunch of weird dependency issues. This is my print out:

`
root@62f92b70527b:/packages# dpkg -i dh-virtualenv_1.2.1-1_all.deb
Selecting previously unselected package dh-virtualenv.
(Reading database ... 6829 files and directories currently installed.)
Preparing to unpack dh-virtualenv_1.2.1-1_all.deb ...
Unpacking dh-virtualenv (1.2.1-1) ...
dpkg: dependency problems prevent configuration of dh-virtualenv:
 dh-virtualenv depends on python3:any.
 dh-virtualenv depends on perl:any.
 dh-virtualenv depends on sphinx-rtd-theme-common (>= 0.4.3+dfsg); however:
  Package sphinx-rtd-theme-common is not installed.
 dh-virtualenv depends on virtualenv | python3-virtualenv (>= 1.7) | python3-venv; however:
  Package virtualenv is not installed.
  Package python3-virtualenv is not installed.
  Package python3-venv is not installed.

dpkg: error processing package dh-virtualenv (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dh-virtualenv
`

I am running from within a docker container using the latest python install.

**Comment by jhermann** [comment]
dpkg is not apt, dependencies need to be there already (e.g. install old dh-venv, **then** upgrade via dpkg).

Docker: see https://github.com/1and1/debianized-jupyterhub/blob/master/Dockerfile.build#L86-L93
