### ISSUE TITLE
Support disabling pip in installed virtualenvs

### ISSUE THREAD

**Issue by OddBloke** [spotify/dh-virtualenv#337]
We use `dh-virtualenv` to allow us to handle Python applications the same way as we handle all of our other packaged applications: as Debian packages.  It follows, for us, that the appropriate way to bump up the version of an application's dependency is to build a new Debian package containing that dependency, rather than to mutate the deployed virtualenv.

To make it harder for us to accidentally mutate virtualenvs in production, it would be good if we could ask `dh-virtualenv` to build them with an inert pip. `pip ...` could emit something along the lines of "This virtualenv is installed via the $PKG Debian package: install a new version of that package to modify this virtualenv."

**Comment by OddBloke** [comment]
(This occurred to me when I hit the error in #338 and realised that pip being broken could be a feature rather than a bug. :grin:)

**Comment by OddBloke** [comment]
For now I've achieved this by adding a `debian/inert-pip` script which just echoes a message, and appending this to `override_dh_virtualenv`:

```sh
for pip_binary in ./debian/<PKG>/opt/venvs/<PKG>/bin/pip*; do cp -v ./debian/inert-pip $${pip_binary}; done
```

**Comment by nailor** [comment]
Thanks for an another great informative issue!

I think the inert pip could potentially be something people would appreciate. While I don’t think it makes sense to destroy pip by default, maybe this could be documented in the Packaging Cookbook section?

**Comment by jhermann** [comment]
Does not prevent `python3 -m pip ...`.

Way better is `$(DH_VENV_DIR)/bin/python -m pip uninstall pip`. Yes, that works. Try it AFTER calling dh_virtualenv in a `override_dh_virtualenv:`.

**Comment by OddBloke** [comment]
> Way better is `$(DH_VENV_DIR)/bin/python -m pip uninstall pip`. Yes, that works. Try it AFTER calling dh_virtualenv in a `override_dh_virtualenv:`.

Thanks, this is way better!

**Comment by OddBloke** [comment]
I've opened up #340 to add this to the docs

(For anyone driving by who isn't going to go and read the docs, know that you'll want to add `--yes` to the `pip uninstall` invocation proposed above.)
