### ISSUE TITLE
Question: Why skip package that start with python3?

### ISSUE THREAD

**Issue by CommunityX** [spotify/dh-virtualenv#343]
Debian and ubuntu use it for example
python-requests  and python3-requests

Currently in debhelper package that start with python3 are skipped.   Is this cause dh-virtualenv  doesn't support python3 building at its core ?  cause it does with the --python argument.

**Comment by nailor** [comment]
Hi,

I’m not entirely sure what you refer to with skipping packages that start with python3. However I can answer the question about package naming.

In Debian packages naming convention of `python-*` is used for Python libraries that will be installed system wide, usually somewhere under `/usr/lib`. Dh-virtualenv does not create reusable Python libraries but rather installations of a whole application. In that light it does not make sense to name packages produced with it with the `python-` prefix.

**Comment by CommunityX** [comment]
im refering to those 2 lines
https://github.com/spotify/dh-virtualenv/blob/6d5a12aae672fc7204ba4093e882cef871d58b14/dh_virtualenv/debhelper.py#L54
https://github.com/spotify/dh-virtualenv/blob/6d5a12aae672fc7204ba4093e882cef871d58b14/dh_virtualenv/debhelper.py#L68

ok it actually make sence that we dont realy require the python prefix.
