### ISSUE TITLE
Is dh-virtualenv working with pyproject.toml

### ISSUE THREAD

**Issue by ikus060** [spotify/dh-virtualenv#366]
I have a project that I want to migrate from setup.py to pyproject-toml when the debian packaging makes use of dh-virtualenv. But I'm running into weird problems. So the quick question. Is dh-virtuelenv working with pyproject.toml ? Since which version ?

Reading the doc:

> The project must have a setup.py file in the root of the project. dh_virtualenv will run setup.py install to add your project to the virtualenv.

**Comment by karibou** [comment]
I don't know if it can help, but I'm packaging a project which only uses pyproject.toml and no setup.py. dh_virtualenv works fine for me, as long as there is a [project] table in my pyproject.toml file.

**Comment by ikus060** [comment]
This is useful, so in theory it should work.

Thanks for your feedback.
