### ISSUE TITLE
Reuse created virtualenv on multiple binary packages

### ISSUE THREAD

**Issue by ccortezia** [spotify/dh-virtualenv#39]
When more than one binary package is defined on debian/control, dh_virtualenv does not reuse the frozen virtualenv it creates. 

In my usage scenario, the difference between "binaries" are solely on debian/xxx.install and debian/xxx.postinst files, but since the virtualenv is recreated for each define binary, the build takes much longer. 

Add to it the fact that I am cross compiling using  a slow ARM machine (QEMU / raspberry), and it gets real bad.

**Comment by zgoda-mobica** [comment]
Hi @ccortezia could you please share some hints for qemu-based build config for dh-virtualenv? I'm struggling to set this up, I can build my package for amd64 on amd64 system but I seem to have problems with cross-building for armhf. I can build armhf package with pbuilder but I would rather like to not mix these 2 setups.

**Comment by ccortezia** [comment]
Hey @zgoda-mobica, it has been a while since I went through this. What I barely remember doing was launching an arm qemu instance, triggering dh-virtualenv inside it and then collecting the resulting .deb package. It was possible to automate and make it part of my build chain. I am sorry I don't remember more details to share. One thing to note is that for some reason the process was really slow, as I could not find a way to make it run faster at that time.

**Comment by zgoda-mobica** [comment]
Hi @ccortezia, tried that already and it was much slower than my approach with pbuilder. Thank you for your help. :)
