### ISSUE TITLE
Create PPA for Ubuntu Trusty

### ISSUE THREAD

**Issue by nailor** [spotify/dh-virtualenv#55]
In order for it to be easier to install 0.7 (and newer) to Trusty, create a PPA for that. Maybe even support Precise.

**Comment by haizaar** [comment]
This PPA is not maintained anymore. The current package version is still 0.9 (and not 0.9.1) and it does not supply packages for the latest ubuntu 15.04.

Please reopen the ticket.

Thanks to @guilhem for supporting it so far!

**Comment by nailor** [comment]
Good observation! I'll look into the PPA :)

**Comment by guilhem** [comment]
As said on previous issue:
My PPA is maintain by a "team" (where I'm alone for the moment...).
But I will be very happy to include who want to contribute!
