### ISSUE TITLE
split build and install part

### ISSUE THREAD

**Issue by guilhem** [spotify/dh-virtualenv#59]
For the moment, `dh-virtualenv` is running at the end of "install" part of debhelper.

It would be great to be able to have a "build" part. I explain:
- In build part, we are creating a virtualenv in a temporary dir (with packages etc).
- In install part, we are coping this venv to the correct place in package.

We are needing this, because we have to do some special command on venv to be able to build our software.
For example, to do a `collectstatic` on a django app we needing a complete venv. This static will be put in the right place in package with `mypackage-static.install` file.

I begin to work on it, here is for example command I used in `python_virtualenv.pm`:

``` perl
insert_before("dh_auto_build", "dh_virtualenv_build");
insert_before("dh_auto_install", "dh_virtualenv_install");
insert_before("dh_clean", "dh_virtualenv_clean");
```

**Comment by brianglass** [comment]
My solution to this was to do a collectstatic in the rules file just before the dh_virtualenv line. Then I moved the staticfiles directory and corresponding setting to my app directory and added the directory into the MANIFEST.in. This caused the setup.py to install the staticfiles dir into the virtualenv.
