### ISSUE TITLE
Please document USENETWORK=yes

### ISSUE THREAD

**Issue by hashar** [spotify/dh-virtualenv#77]
Whenever using pbuilder (such as via git-buildpackage) we definitely need a network access to fetch dependencies from pypi. I eventually found the solution on #70 which is to pass `USENETWORK=yes`.

The variable is explained in `man 5 pbuilderrc`:

> USENETWORK=no
> 
> Specify  yes  when  you do not want to disable network access during build.  Network is not available on a Debian buildd, so you might want to keep the default.  Disabling network access currently only works on Linux.

I have set it globally in my ~/.pbuiderrc , since apparently passing it to git-buildpackage / cowbuilder does not work :(

**Comment by nailor** [comment]
I'm bit torn between documenting these and having this issue as the documentation (i.e. people googling would hit this).

Pros on documenting: pbuilder is pretty popular build system, so having a troubleshooting section with this information might be valuable to people

Cons on including this into the documentation: I'm not sure if the documentation should cover the quirks of the different build systems or should the knowledge of the build system be something we assume the user knows.

Thoughts?

**Comment by hashar** [comment]
I am not that experienced in Debian packaging, but it surely took me more than a couple hours to figure out that networking was disabled and how to enable it.

When building package, pbuilder disable networking by default since the Debian buildd system don't have any, so there is never a case to require networking when the intent is to upload the package to the Debian project. Since dh-virtualenv definitely require network access and the build failure is not trivial to figure out (I just add a temporary resolution failure for pypi.python.org), I am sure others users will hit the same wall.

I understand there are several different build systems, each coming with their own quirks. pbuilder USENETWORK is obfuscated enough that it would certainly save users time to document it.

The pbuilder option is documented in `man 5 pbuilderrc` and I haven't figure out how to pass it as an env variable, I had to `echo USENETWORK=yes >> /root/.pbuilderrc`.  There might be a way to pass it from the command line when invoking `git-buildpackage` but I haven't figured it out yet :(

**Comment by nailor** [comment]
Given that there are a few other troubleshooting things, would you be interested in creating a trouble shooting page in documentation and start it with this? I'll see if there's something else to add into it too.

**Comment by hashar** [comment]
Sure, I will be more than happy to add some more documentation based on my first experience.

If you point me to other troubleshoot or past issues, I will integrate them.
