### ISSUE TITLE
Release new version to publish -S/--use-system-packages

### ISSUE THREAD

**Issue by hashar** [spotify/dh-virtualenv#78]
Would you mind tagging a new version that would contains the recent "-S/--use-system-packages" feature?  Once tagged, the Debian package can be easily refreshed and thus the change be made available easily to the whole community.

**Comment by kataev** [comment]
Oh you, just use search #69

**Comment by hashar** [comment]
I did use search and indeed found the workaround described at #69 in October 2014. The feature request has been implemented meanwhile in December 2014 with af8a7d5c65 which is post the 0.8 tag.  So I am merely requesting a new tag that would include the feature :)

**Comment by nailor** [comment]
Hi @hashar,

I'll push out a new version, thanks for the ticket!

**Comment by nailor** [comment]
New version is now in Debian mentors queue, waiting to be approved!

**Comment by hashar** [comment]
You are awesome! Thank you very much.
