### ISSUE TITLE
Should automatically honor DEB_BUILD_OPTIONS=nocheck

### ISSUE THREAD

**Issue by hashar** [spotify/dh-virtualenv#79]
dh-virtualenv has a `--no-test` parameter to skip runing tests, it should also skip test whenever DEB_BUILD_OPTIONS contains the tag `nocheck`. The tag is standardized in [Debian Policy 4.9.1 debian/rules and DEB_BUILD_OPTIONS](https://www.debian.org/doc/debian-policy/ch-source.html).

A workaround is:
```
override_dh_virtualenv:
ifneq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
    $(eval DH_VIRTUALENV_NO_TEST := "--no-test")
endif
    dh_virtualenv $(DH_VIRTUALENV_NO_TEST)
```

**Comment by nailor** [comment]
Good catch! I'll patch this in :)
