### ISSUE TITLE
Consider changing install location

### ISSUE THREAD

**Issue by vilius-g** [spotify/dh-virtualenv#82]
Currently `dh-virtualenv` installs packages into `/usr/share/python/$packagename`. As far as I understand `/usr/share/python` is for system python packages only and other packages should be installed somewhere else (`/usr/share/$packagename` maybe?).

Installing into `/usr/share/python` may break system python packages.

##### For example, I have run into this issue:
I have a `dh-virtualenv` based package that includes `gunicorn`. When it is installed, `python-minimal` package cannot be upgraded or reinstalled: 
```
Setting up python-minimal (2.7.3-0ubuntu2.2) ...
dpkg: error processing python-minimal (--configure):
 subprocess installed post-installation script returned error exit status 1
```
The reason is this line in `python-minimal.postinst script`:
```
python2.7 -m compileall /usr/share/python/ >/dev/null
```
Which fails with this:
```
[...]
Compiling /usr/share/python/<my-package-name>/lib/python2.7/site-packages/gunicorn/workers/_gaiohttp.py ...
SyntaxError: ('invalid syntax', ('/usr/share/python/<my-package-name>/lib/python2.7/site-packages/gunicorn/workers/_gaiohttp.py', 68, 26, '                yield from self.wsgi.close()\n'))
[...]
```
To upgrade `python-minimal` package I need to remove my package first and then reinstall it after. Which is neither obvious nor convenient.

**Comment by nailor** [comment]
Good point and a valid case why this is broken

I'll look into changing the install location. It can cause some inconvenience and backwards compatibility might be an issue (all the sudden your install/link files just stop working). Pull requests are accepted too :)

**Comment by jhermann** [comment]
While we're at it, why not go all the way *outside* of Debian policy world and into /opt/dh-virtualenv as a base dir? After all, the resulting packages aren't "real" (policy-conforming) packages, they're just using the archive format and other conveniences coming with dpkg/apt. That also would stop Lintian to complain about stuff that might otherwise indicate a broken package (except I think it has a rule about /opt files).

**Comment by nailor** [comment]
Yeah, lintian would be a bit sad for opt. Of course one should not probably be too touchy about lintian in the case of output of dh-virtualenv, so maybe going to `/opt` is a nice way to go

**Comment by jhermann** [comment]
You now have the *option* to change the installation root, so this could be closed unless the *default* is to be changed (the OP's problem is now easily solved).

**Comment by nailor** [comment]
@jhermann has a point. Closing this issue for now as it can be wrked around
