### ISSUE TITLE
Bad VIRTUAL_ENV path in installed activate scripts

### ISSUE THREAD

**Issue by agilevic** [spotify/dh-virtualenv#88]
Resulting activate script (and activate.csh, activate.fish) contains VIRTUAL_ENV variable prefixed with the path where the script was built. Instead that variable should be set to the installation root, as set with $DH_VIRTUALENV_INSTALL_ROOT/my-package (or /usr/share/python/my-package by default)

For example if setup.py for my-package is in /home/agilevic/hgdev/my-package, running dpkg-buildpackage -us -uc results in activate script's VIRTUAL_ENV set to /home/agilevic/hgdev/my-package/debian/my-package/usr/share/python/my-package; should be VIRTUAL_ENV=/usr/share/python/my-package.

Resulting virtualenvs are unusable.

**Comment by nailor** [comment]
I'm not seeing this issue with the `activate`, but it seems to be with `activate.csh` and `activate.fish`.

Thanks for the report, I'll inspect further!

**Comment by nailor** [comment]
This was fixed by #111
