### ISSUE TITLE
Creating a .desktop app

### ISSUE THREAD

**Issue by benjaminirving** [spotify/dh-virtualenv#92]
dh-virtualenv is working very well for packaging python projects so thanks very much. 

I would now like to include a desktop shortcut to my app using a .deskop file. What is the best way to include this with dh-virtualenv? 

My knowledge of debian packaging is very limited.

**Comment by nailor** [comment]
Hi,

I'm not too familiar with packaging to desktop, but `xdg-desktop-icon` might be something that might fit the bill. See here for more: https://superuser.com/questions/76148/automatically-install-a-desktop-launcher-for-an-ubuntu-deb-package

**Comment by benjaminirving** [comment]
Thanks. 

I actually founded that including an install file in the debian folder did the trick

```
# install bash script to usr/bin
# usr/local/bin seems to only be for self compiled stuff
debian/pkviewer2 usr/bin
# Copy application file and icon
debian/PKView.desktop usr/share/applications
debian/pkviewer2.png usr/share/icons/hicolor/48x48/apps
```

Apologies if this issue was off topic as I see this has more to do with python and debian, than dh-virtualenv

**Comment by benjaminirving** [comment]
I've created a little example for myself that illustrates using dh-virtualenv to package a GUI application for Ubuntu that installs a shortcut, icon etc. 

Leaving here if of interest:
https://github.com/benjaminirving/python-debian-packaging-example
http://blog.birving.com/2015/10/creating-debian-application-from-python.html
