### ISSUE TITLE
Increase a build speed by caching virtualenv dependencies

### ISSUE THREAD

**Issue by ykhrustalev** [spotify/dh-virtualenv#94]
It takes long when requirements for the project include several binary packages, like uwsgi, crypto and postgresql. Build time significantly increase.

What if there would be some way to eliminate re-building from scratch the all those things each time by using for instance https://github.com/paylogic/pip-accel?

**Comment by ykhrustalev** [comment]
It could be an option to specify which `pip` runnable to use

**Comment by ykhrustalev** [comment]
For now found a way to use wheel packages, but that has some requirements:

* wheel package installed system wide
* virtualenv is built with `--use-system-packages`

```
#!/usr/bin/make -f

%:
	dh $@ --with python-virtualenv


WHEEL_ROOT:=	/var/wheelhouse

override_dh_virtualenv:
	pip wheel -w=$(WHEEL_ROOT) -f $(WHEEL_ROOT) -r requirements.txt
	dh_virtualenv \
		--use-system-packages \
		--extra-pip-arg "--use-wheel" \
		--extra-pip-arg "--find-links=$(WHEEL_ROOT)"
```

**Comment by jhermann** [comment]
Pip7 has wheel caching, so simply use that.

**Comment by nailor** [comment]
Closing this since it is fixable by using fairly recent pip or by providing a local pypi mirror
