### ISSUE TITLE
Work around too long shebang lines when installing

### ISSUE THREAD

**Issue by nailor** [spotify/dh-virtualenv#97]
This issue is related to #10, but since this is an issue in a different place of the pipeline (in build rather than after installation), it's filed separately.

Some installation scripts might want to run other scripts when running `setup.py install`. This can be problematic if they want to run a script that got installed by a dependency, since the shebang of those scripts is `${BUILDDIR}/usr/share/python/<packagename>/bin/python`. This easily grows over 127 characters, effectively halting the build.

**Comment by vnaydionov** [comment]
Can you consider adding another cli option or two to specify virtualenv build dir explicitly or to ask `dh_virtualenv` to allocate one in `/tmp`?

**Comment by nailor** [comment]
I'd assume a build system being used could handle that, I'm pretty sure there's a debhelper option to tell where to build. Or were you thinking this as a some other kind of fix?

A side note btw, I'm thinking of closing this issue. Moving things under `/opt` gave more leverage and I'm quite convinced there's no easy way of solving this issue.

**Comment by vnaydionov** [comment]
I'm talking of a problem arising during package build process, when paths may be getting too lengthy.
The problem, as I can see from the source code, roots in how value of `self.package_dir` is constructed. It always starts with `debian/` folder, which in turn may be well buried in some CI agent working directory.
What if we could ask `dh-virtualenv` to create a virtualenv elsewhere, say in `/tmp` directory, which will help us avoid subsequent problems with installing things with pip? After the `requirements.txt` is processed, of course, we will have to move the virtualenv to its proper subdirectory within `debian/` folder right before packaging.

**Comment by vnaydionov** [comment]
Looks like the problem I've encountered (with the very creation of a virtualenv inside a deep folder) shows up in Ubuntu 12.04 but not in 14.04 or newer. Other possible solutions: upgrade `python-virtualenv` or Ubuntu.

**Comment by jhermann** [comment]
See #225

**Comment by nailor** [comment]
I believe this is now fixed by upstream pip and the changes in dh-virtualenv. Let me know if we still need to change behaviour of dh-virtualenv to take these long shebangs into account.
